import { MonthCloseButton } from "@/components/backend-action-controls";
import { compactMoney } from "@/lib/demo-data";
import { Delta, Donut, Meter, PageLead, Panel, SectionHead, SparkBars, StatePill } from "@/components/ui";
import { monthEndForecast } from "@/lib/forecast";
import { groupForecast } from "@/lib/restaurant-controls";
import { getFinancialData } from "@/lib/command-data";

export default async function FinancialsPage(){
 const data=await getFinancialData();const {ctx,outlets,expenses,channelMix,cashReconciliation,monthlyTrend,grossProfit,operatingProfit}=data;
 const revenue=outlets.reduce((a,o)=>a+o.revenue,0),profit=outlets.reduce((a,o)=>a+o.profit,0);
 let liveForecast={mtd:revenue,target:0,daysInMonth:ctx.daysInMonth};let forecastSourceHeld=false;try{liveForecast=await groupForecast(ctx.year,ctx.month,ctx.daysElapsed);}catch(error){forecastSourceHeld=true;console.error("Financial forecast source failed",error)}
 const forecastRevenue=liveForecast.mtd>0?liveForecast.mtd:revenue;const forecastTarget=liveForecast.target>0?liveForecast.target:outlets.reduce((s,o)=>s+(o.target>0?o.revenue/(o.target/100):0),0);
 const forecast=monthEndForecast({mtdRevenue:forecastRevenue,targetRevenue:forecastTarget,elapsedDays:Math.max(1,ctx.daysElapsed),daysInMonth:liveForecast.daysInMonth});
 const openCash=cashReconciliation.filter(c=>!c.closed||Math.abs(c.variance)>1000);const expenseTotal=expenses.reduce((s,e)=>s+e.amount,0);
 if(!outlets.length)return <><PageLead code="03" eyebrow="FINANCE / GROUP P&L" title="Profitability without spreadsheet fog." copy="The finance backend is ready. Load outlet and monthly financial data to activate this command view."/><Panel><SectionHead no="01" kicker="WAITING FOR DATA" title="No production financial records yet"/><p>Use Imports → Monthly financials, Daily sales, Expenses and Cash reconciliation.</p></Panel></>;
 return <>
  <PageLead code="03" eyebrow={`FINANCE / GROUP P&L / ${ctx.label}`} title="Profitability without spreadsheet fog." copy="A single monthly operating picture with outlet drill-down, cost pressure, cash reconciliation, channel contribution and controlled month close." action={<MonthCloseButton year={ctx.year} month={ctx.month} closed={ctx.status==="closed"}/>} meta={<><span>MONTH {ctx.status.toUpperCase()}</span><span>{cashReconciliation.length-openCash.length}/{cashReconciliation.length||0} CASH RECONCILED</span><span>FRESH MFA REQUIRED TO CLOSE</span></>}/>
  <div className="finance-kpis"><div><span>NET REVENUE</span><strong>{compactMoney(revenue)}</strong><b>{ctx.dataMode.toUpperCase()}</b></div><div><span>GROSS PROFIT</span><strong>{compactMoney(grossProfit)}</strong><b>{revenue?`${(grossProfit/revenue*100).toFixed(1)}%`:"0%"}</b></div><div><span>OPERATING PROFIT</span><strong>{compactMoney(operatingProfit)}</strong><b>{revenue?`${(operatingProfit/revenue*100).toFixed(1)}%`:"0%"}</b></div><div><span>NET PROFIT</span><strong>{compactMoney(profit)}</strong><b>{revenue?`${(profit/revenue*100).toFixed(1)}%`:"0%"}</b></div><div><span>NET MARGIN</span><strong>{revenue?(profit/revenue*100).toFixed(1):"0.0"}%</strong><b>MTD</b></div><div><span>OPEN CASH VAR.</span><strong>{compactMoney(openCash.reduce((s,c)=>s+Math.abs(c.variance),0))}</strong><b>{openCash.length} OUTLETS</b></div></div>
  {forecastSourceHeld&&<div className="data-held-banner"><b>FORECAST SOURCE HELD</b><span>Daily run-rate query is unavailable. The forecast below is using the loaded outlet revenue and target records only.</span></div>}
  <div className={`forecast-command is-${forecast.status}`}><div><span>MONTH-END FORECAST</span><strong>{compactMoney(forecast.projectedRevenue)}</strong><small>PROJECTED {ctx.label} REVENUE</small></div><div><span>TARGET</span><strong>{compactMoney(forecastTarget)}</strong><small>{forecast.targetPct.toFixed(1)}% ACHIEVED MTD</small></div><div><span>PROJECTED GAP</span><strong className={forecast.gap<0?"bad-text":""}>{forecast.gap>=0?"+":""}{compactMoney(forecast.gap)}</strong><small>{forecast.status.replace("_"," ").toUpperCase()}</small></div><div><span>REQUIRED / DAY</span><strong>{compactMoney(forecast.requiredDailyRevenue)}</strong><small>FOR REMAINING {Math.max(0,ctx.daysInMonth-ctx.daysElapsed)} DAYS</small></div><div className="forecast-rail"><i><b style={{width:`${Math.min(100,forecast.pacePct)}%`}}/></i><span>PROJECTED PACE {forecast.pacePct.toFixed(1)}%</span></div></div>
  <div className="finance-grid command-gap">
   <Panel className="pnl-panel"><SectionHead no="01" kicker="GROUP P&L" title="Operating statement"/><div className="pnl-table"><div className="pnl-row is-major"><span>Net revenue</span><strong>{compactMoney(revenue)}</strong><b>100.0%</b></div><div className="pnl-row is-major"><span>Gross profit</span><strong>{compactMoney(grossProfit)}</strong><b>{revenue?(grossProfit/revenue*100).toFixed(1):"0.0"}%</b></div>{expenses.map(e=><div className="pnl-row" key={e.category}><span>{e.category}</span><strong>-{compactMoney(e.amount)}</strong><b>{e.pct.toFixed(1)}%</b></div>)}{!expenses.length&&<div className="pnl-row"><span>Itemised expenses</span><strong>{compactMoney(expenseTotal)}</strong><b>IMPORT LEDGER</b></div>}<div className="pnl-row is-subtotal"><span>Operating profit</span><strong>{compactMoney(operatingProfit)}</strong><b>{revenue?(operatingProfit/revenue*100).toFixed(1):"0.0"}%</b></div><div className="pnl-row is-final"><span>Net profit</span><strong>{compactMoney(profit)}</strong><b>{revenue?(profit/revenue*100).toFixed(1):"0.0"}%</b></div></div></Panel>
   <Panel className="cost-pressure"><SectionHead no="02" kicker="CONTROL LIMITS" title="Cost pressure"/><div className="cost-pressure-list">{expenses.slice(0,7).map((e,i)=><div key={e.category}><span><b>C{String(i+1).padStart(2,"0")}</b>{e.category}</span><Meter value={Math.min(100,e.pct*2.6)} tone={e.delta>8?"red":"teal"}/><strong className={e.delta>8?"bad-text":""}>{e.delta>0?"+":""}{e.delta.toFixed(1)}%</strong></div>)}</div></Panel>
   <Panel className="outlet-profitability"><SectionHead no="03" kicker="OUTLET PROFITABILITY" title="Where group profit is created"/><div className="profitability-table"><div className="profit-head"><span>OUTLET</span><span>REVENUE</span><span>NET PROFIT</span><span>MARGIN</span><span>30D</span></div>{[...outlets].sort((a,b)=>b.profit-a.profit).map((o,i)=><div className="profit-row" key={o.id}><span><b>{String(i+1).padStart(2,"0")}</b><strong>{o.name}</strong></span><em>{compactMoney(o.revenue)}</em><em className={o.profit<0?"bad-text":""}>{compactMoney(o.profit)}</em><strong className={o.margin<18?"bad-text":""}>{o.margin}%</strong><Delta value={o.delta}/></div>)}</div></Panel>
   <Panel className="channel-economics"><SectionHead no="04" kicker="CHANNEL ECONOMICS" title="Revenue is not contribution"/><div className="channel-block"><Donut center={compactMoney(channelMix.reduce((s,c)=>s+c.revenue,0))} sub="NET REVENUE" segments={channelMix.map((c,i)=>({value:c.share,className:`seg-${i+1}`}))}/><div className="channel-list">{channelMix.map((c,i)=><div key={c.name}><i className={`dot dot-${i+1}`}/><span><strong>{c.name}</strong><small>{c.share}% of channel revenue</small></span><b>{c.contribution}% after commission</b></div>)}</div></div></Panel>
   <Panel className="cash-recon"><SectionHead no="05" kicker="CASH RECONCILIATION" title="Expected vs deposited"/><div className="cash-table"><div className="cash-head"><span>OUTLET</span><span>EXPECTED</span><span>DEPOSITED</span><span>VARIANCE</span><span>STATUS</span></div>{cashReconciliation.map(c=><div className="cash-row" key={c.outlet}><b>{c.outlet}</b><span>{compactMoney(c.expected)}</span><span>{compactMoney(c.deposited)}</span><strong className={Math.abs(c.variance)>2000?"bad-text":""}>{compactMoney(c.variance)}</strong><StatePill state={c.status}>{c.closed?"CLOSED":"OPEN"}</StatePill></div>)}</div></Panel>
   <Panel className="month-close"><SectionHead no="06" kicker="CONTROLLED CLOSE" title={`${ctx.label} close readiness`}/><div className="close-status"><div><span>Daily sales loaded</span><Meter value={forecastRevenue>0?100:0}/></div><div><span>Expense ledger</span><Meter value={expenses.length?100:0}/></div><div><span>Cash reconciliation</span><Meter value={cashReconciliation.length?Math.round((cashReconciliation.length-openCash.length)/cashReconciliation.length*100):0} tone={openCash.length?"red":"teal"}/></div><div><span>Monthly P&L</span><Meter value={revenue>0?100:0}/></div><div><span>Owner review</span><Meter value={ctx.status==="closed"?100:50} tone={ctx.status==="closed"?"teal":"red"}/></div></div><div className="close-callout"><strong>{ctx.status==="closed"?"Month is locked":"Owner close is pending"}</strong><p>{ctx.status==="closed"?"Protected monthly financial records are database-locked against ordinary rewrites.":"Close only after sales, expenses, cash and payroll are reconciled."}</p></div></Panel>
   <Panel className="month-history"><SectionHead no="07" kicker="6 MONTH TREND" title="Scale and profit"/><div className="history-bars">{monthlyTrend.map(m=><div key={m.month}><span>{m.month}</span><i style={{height:`${Math.max(2,m.revenue/1.5)}px`}}/><b style={{height:`${Math.max(2,Math.abs(m.profit)*3)}px`}}/><small>₹{m.revenue}L</small></div>)}</div><div className="history-legend"><span><i/> Revenue</span><span><i/> Profit</span></div><SparkBars values={monthlyTrend.map(m=>Math.max(0,m.margin*6))}/></Panel>
  </div>
 </>;
}
