import { z } from "zod";
import { requireApiProfile } from "@/lib/access-control";
import { canManageSecurity } from "@/lib/authz";
import { recordSecurityEvent } from "@/lib/audit";
import { db } from "@/lib/db";
import { hasFreshFinancialMfa } from "@/lib/mfa";
import { enforceSameOrigin, readJsonWithLimit, requestParseError } from "@/lib/http-security";
const schema=z.object({action:z.enum(["approve","deny","revoke"]),label:z.string().trim().max(80).optional()});
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const same=enforceSameOrigin(req);if(same)return same;const access=await requireApiProfile("/api/admin/devices");if("response" in access)return access.response;const profile=access.profile;if(!canManageSecurity(profile.role))return Response.json({error:"Forbidden"},{status:403});if(!(await hasFreshFinancialMfa()))return Response.json({error:"Fresh MFA required",code:"MFA_FRESH_REQUIRED"},{status:428});try{const parsed=schema.safeParse(await readJsonWithLimit(req,2048));if(!parsed.success)return Response.json({error:"Invalid device action"},{status:400});const {id}=await params;const status=parsed.data.action==="approve"?"approved":parsed.data.action==="deny"?"denied":"revoked";const rows=await db()`UPDATE approved_devices SET status=${status},label=COALESCE(${parsed.data.label||null},label),approved_by=CASE WHEN ${status}='approved' THEN ${profile.id} ELSE approved_by END,approved_at=CASE WHEN ${status}='approved' THEN NOW() ELSE approved_at END,revoked_at=CASE WHEN ${status}='revoked' THEN NOW() ELSE revoked_at END WHERE id=${id} RETURNING id,user_id,status`;if(!rows.length)return Response.json({error:"Device not found"},{status:404});if(status!=="approved")await db()`UPDATE active_sessions SET revoked_at=NOW(),revoke_reason='device_${status}' WHERE device_id=${id} AND revoked_at IS NULL`;await recordSecurityEvent(`device_${status}`,{severity:status==="approved"?"info":"watch",metadata:{deviceId:id,targetUserId:String(rows[0].user_id)}});return Response.json({ok:true,status},{headers:{"Cache-Control":"no-store"}});}catch(error){const response=requestParseError(error);if(response)return response;throw error;}}
