import { compactMoney } from "@/lib/demo-data";
import { Delta, Meter, PageLead, Panel, SectionHead, StatePill } from "@/components/ui";
import { getProcurementData } from "@/lib/command-data";
export default async function ProcurementPage(){const {ctx,vendors,payables}=await getProcurementData();const spend=vendors.reduce((s,v)=>s+v.spend,0),avgFill=vendors.filter(v=>v.fillRate>0).length?Math.round(vendors.filter(v=>v.fillRate>0).reduce((s,v)=>s+v.fillRate,0)/vendors.filter(v=>v.fillRate>0).length):0;return <>
<PageLead code="08" eyebrow={`PROCUREMENT / VENDORS / ${ctx.label}`} title="Buy with memory, not guesswork." copy="Track vendor spend, payment exposure and supplier performance across the group." action={<a className="command-button" href="/imports">IMPORT PURCHASES <span>→</span></a>} meta={<><span>PURCHASE HISTORY</span><span>PAYABLES</span><span>SUPPLIER PERFORMANCE</span></>}/>
<div className="procurement-kpis"><div><span>TRACKED SPEND</span><strong>{compactMoney(spend)}</strong><small>MTD PURCHASES</small></div><div><span>ACTIVE VENDORS</span><strong>{vendors.length}</strong><small>VENDOR MASTER</small></div><div><span>SPEND WATCH</span><strong>{vendors.filter(v=>v.change>10).length}</strong><small>&gt;10% VS PRIOR MONTH</small></div><div><span>AVG FILL RATE</span><strong>{avgFill?`${avgFill}%`:"—"}</strong><small>{avgFill?"RECORDED VENDORS":"OPTIONAL VENDOR KPI"}</small></div><div><span>OPEN PAYABLES</span><strong>{compactMoney(payables.open)}</strong><small>{payables.invoices} INVOICES</small></div></div>
<div className="procurement-grid command-gap"><Panel className="vendor-panel"><SectionHead no="01" kicker="VENDOR BOOK" title="Spend and reliability"/><div className="vendor-table"><div className="vendor-head"><span>VENDOR / CATEGORY</span><span>MTD SPEND</span><span>SPEND MOVE</span><span>FILL RATE</span><span>RELIABILITY</span><span>TERMS</span><span>STATE</span></div>{vendors.map(v=><div className="vendor-row" key={v.id}><span><b>{v.id}</b><strong>{v.name}</strong><small>{v.category}</small></span><b>{compactMoney(v.spend)}</b><span><Delta value={v.change}/></span><span>{v.fillRate?<Meter value={v.fillRate} tone={v.fillRate<92?"red":"teal"}/>:<em>—</em>}</span><span>{v.reliability?<Meter value={v.reliability}/>:<em>—</em>}</span><span>{v.terms}</span><span><StatePill state={v.status}>{v.status.toUpperCase()}</StatePill></span></div>)}</div></Panel>
<Panel className="price-watch-panel"><SectionHead no="02" kicker="SPEND WATCH" title="Vendor movement vs prior month"/><div className="price-watch">{vendors.slice(0,6).map((v,i)=><div key={v.id}><span><b>P{String(i+1).padStart(2,"0")}</b>{v.name}</span><strong className={v.change>10?"bad-text":v.change<0?"good-text":""}>{v.change>0?"+":""}{v.change.toFixed(1)}%</strong><small>SPEND MOVE</small></div>)}</div></Panel>
<Panel className="payables-panel"><SectionHead no="03" kicker="PAYABLES" title="Open purchasing exposure"/><div className="payable-stack"><div><span>Pending / partial invoices</span><strong>{payables.invoices}</strong><b>{compactMoney(payables.open)}</b></div><div><span>Disputed exposure</span><strong>—</strong><b className="bad-text">{compactMoney(payables.disputed)}</b></div></div></Panel>
<Panel className="supplier-risk" tone="cream"><SectionHead no="04" kicker="SUPPLIER CONCENTRATION" title="Where purchasing is exposed"/><div className="supplier-risk-list">{vendors.slice(0,5).map((v,i)=><div key={v.id}><b>{String(i+1).padStart(2,"0")}</b><span><strong>{v.name}</strong><small>{v.category} · {compactMoney(v.spend)}</small></span><i><b style={{width:`${spend?Math.min(100,v.spend/spend*300):0}%`}}/></i><em>{spend?Math.round(v.spend/spend*100):0}%</em></div>)}</div></Panel></div></>}
