import "server-only";
import { db } from "@/lib/db";
import * as demo from "@/lib/demo-data";
import type { Outlet, OutletState } from "@/lib/demo-data";
import { demoDataAllowed } from "@/lib/runtime-mode";

export type ReportingContext={year:number;month:number;label:string;daysElapsed:number;daysInMonth:number;status:"open"|"closing"|"closed";periodId:string|null;dataMode:"live"|"demo"|"empty"};
export type ChannelRow={name:string;share:number;revenue:number;contribution:number;orders:number;commission:number};
export type ExpenseRow={category:string;amount:number;pct:number;delta:number;status:"ahead"|"steady"|"watch"};
export type CashRow={outlet:string;expected:number;deposited:number;variance:number;status:"steady"|"watch"|"critical";closed:boolean};
export type MonthlyTrendRow={month:string;revenue:number;profit:number;margin:number};
export type InventoryRiskRow={item:string;sku:string;category:string;outlets:number;days:number;variance:number;stockValue:number;action:string};
export type VendorRow={id:string;name:string;category:string;spend:number;change:number;reliability:number;fillRate:number;terms:string;status:"ahead"|"steady"|"watch"};
export type MenuItemRow={code:string;name:string;category:string;units:number;revenue:number;foodCost:number;contribution:number;delta:number;rank:number;state:OutletState};
export type MenuCategoryRow={name:string;sales:number;units:number;mix:number;margin:number;delta:number};
export type TaskRow={id:string;title:string;outlet:string;owner:string;due:string;priority:string;status:string;linked:string};
export type DocumentRow={id:string;name:string;type:string;scope:string;owner:string;updated:string;status:string};
export type ImportHistoryRow={file:string;type:string;rows:number;accepted:number;rejected:number;status:string;at:string};
export type ActivityRow={time:string;actor:string;action:string;target:string;type:string};
export type AlertRow={id:string;severity:string;outlet:string;title:string;detail:string;age:string;owner:string};

const monthFmt=new Intl.DateTimeFormat("en-US",{month:"short",timeZone:"Asia/Kolkata"});
const monthLongFmt=new Intl.DateTimeFormat("en-US",{month:"long",year:"numeric",timeZone:"Asia/Kolkata"});
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:0;}
function round(v:number,d=1){const m=10**d;return Math.round(v*m)/m;}
function isoDate(v:unknown){if(!v)return "";const d=new Date(String(v));return Number.isFinite(d.getTime())?d.toISOString().slice(0,10):String(v).slice(0,10);}
const demoAllowed = demoDataAllowed;
function currentIstParts(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const get=(t:string)=>Number(parts.find(p=>p.type===t)?.value||0);return{year:get("year"),month:get("month"),day:get("day")};}
function labelFor(year:number,month:number){return `${monthFmt.format(new Date(Date.UTC(year,month-1,2))).toUpperCase()} ${year}`;}

export class CommandDataQueryError extends Error {
  constructor() { super("Command Center data could not be loaded"); this.name = "CommandDataQueryError"; }
}
async function safe<T>(fn:()=>Promise<T>,fallback:T):Promise<T>{try{return await fn();}catch(error){console.error("GM command data query failed",error);if(demoAllowed())return fallback;throw new CommandDataQueryError();}}

export async function getReportingContext():Promise<ReportingContext>{
 const now=currentIstParts();
 const rows=await safe(()=>db()`SELECT id::text,year,month,status FROM reporting_periods ORDER BY year DESC,month DESC LIMIT 1`,[] as any[]);
 const r=rows[0];const year=r?Number(r.year):now.year;const month=r?Number(r.month):now.month;const daysInMonth=new Date(Date.UTC(year,month,0)).getUTCDate();const daysElapsed=(year===now.year&&month===now.month)?Math.min(now.day,daysInMonth):daysInMonth;
 const liveCount=await safe(async()=>{const x=await db()`SELECT (SELECT count(*) FROM outlets)+(SELECT count(*) FROM daily_sales)+(SELECT count(*) FROM outlet_monthly_financials) n`;return n(x[0]?.n);},0);
 const dataMode:ReportingContext["dataMode"]=liveCount>0?"live":demoAllowed()?"demo":"empty";
 if(dataMode==="demo")return{year:demo.reportingPeriod.year,month:demo.reportingPeriod.month,label:demo.reportingPeriod.label,daysElapsed:demo.reportingPeriod.daysElapsed,daysInMonth:demo.reportingPeriod.daysInMonth,status:"open",periodId:null,dataMode};
 return{year,month,label:labelFor(year,month),daysElapsed,daysInMonth,status:(r?.status||"open") as ReportingContext["status"],periodId:r?.id||null,dataMode};
}

function stateFor(input:{margin:number;delta:number;profit:number;targetPct:number;foodCost:number}):OutletState{
 if(input.profit<0||input.margin<10||input.foodCost>42)return"critical";
 if(input.margin<18||input.targetPct<75||input.foodCost>36)return"watch";
 if(input.targetPct>=100||input.delta>=6)return"ahead";
 return"steady";
}

export async function getOutlets(ctx?:ReportingContext):Promise<Outlet[]>{
 const c=ctx||await getReportingContext();if(c.dataMode==="demo")return demo.outlets;
 const rows=await safe(()=>db()`WITH curp AS (SELECT id FROM reporting_periods WHERE year=${c.year} AND month=${c.month}), prevd AS (SELECT (${c.year}*12+${c.month}-2) idx), prevp AS (SELECT id FROM reporting_periods p,prevd WHERE (p.year*12+p.month-1)=prevd.idx), staff AS (SELECT home_outlet_id,count(*) FILTER(WHERE status<>'inactive') cnt,max(full_name) FILTER(WHERE status<>'inactive' AND role_title ILIKE '%manager%') manager FROM staff_members GROUP BY home_outlet_id), cash AS (SELECT outlet_id,sum(variance) variance FROM cash_reconciliations WHERE EXTRACT(YEAR FROM business_date)=${c.year} AND EXTRACT(MONTH FROM business_date)=${c.month} GROUP BY outlet_id), cx AS (SELECT DISTINCT ON(outlet_id) outlet_id,(COALESCE(google_rating,swiggy_rating,zomato_rating)) rating FROM customer_experience_monthly c JOIN reporting_periods p ON p.id=c.period_id ORDER BY outlet_id,p.year DESC,p.month DESC), inv AS (SELECT outlet_id,CASE WHEN count(*)=0 THEN 100 ELSE 100.0*count(*) FILTER(WHERE reorder_point IS NULL OR on_hand_qty>=reorder_point)/count(*) END health FROM (SELECT DISTINCT ON(outlet_id,item_id) outlet_id,item_id,on_hand_qty,reorder_point FROM inventory_snapshots ORDER BY outlet_id,item_id,snapshot_date DESC) q GROUP BY outlet_id), aud AS (SELECT DISTINCT ON(outlet_id) outlet_id,overall_score FROM outlet_audits_monthly a JOIN reporting_periods p ON p.id=a.period_id ORDER BY outlet_id,p.year DESC,p.month DESC) SELECT o.id::text uuid,o.code,o.name,o.city,o.opening_date,o.monthly_revenue_target,o.food_cost_target_pct,o.labour_cost_target_pct,COALESCE(f.net_revenue,0) revenue,COALESCE(f.net_profit,0) profit,COALESCE(f.total_orders,0) orders,CASE WHEN COALESCE(f.net_revenue,0)>0 THEN 100.0*f.net_profit/f.net_revenue ELSE 0 END margin,CASE WHEN COALESCE(f.net_revenue,0)>0 THEN 100.0*f.food_cost/f.net_revenue ELSE 0 END food_pct,CASE WHEN COALESCE(f.net_revenue,0)>0 THEN 100.0*f.payroll_cost/f.net_revenue ELSE 0 END labour_pct,COALESCE(pf.net_revenue,0) prev_revenue,COALESCE(t.revenue_target,o.monthly_revenue_target,0) target_revenue,COALESCE(staff.cnt,0) staff,COALESCE(staff.manager,'—') manager,COALESCE(cash.variance,0) cash_variance,COALESCE(cx.rating,0) rating,COALESCE(inv.health,100) inventory_health,COALESCE(aud.overall_score,100) compliance FROM outlets o LEFT JOIN curp ON true LEFT JOIN outlet_monthly_financials f ON f.outlet_id=o.id AND f.period_id=curp.id LEFT JOIN prevp ON true LEFT JOIN outlet_monthly_financials pf ON pf.outlet_id=o.id AND pf.period_id=prevp.id LEFT JOIN outlet_targets t ON t.outlet_id=o.id AND t.period_id=curp.id LEFT JOIN staff ON staff.home_outlet_id=o.id LEFT JOIN cash ON cash.outlet_id=o.id LEFT JOIN cx ON cx.outlet_id=o.id LEFT JOIN inv ON inv.outlet_id=o.id LEFT JOIN aud ON aud.outlet_id=o.id WHERE o.status IN ('active','temporarily_closed') ORDER BY o.name`,[] as any[]);
 return rows.map((r:any)=>{const revenue=n(r.revenue),profit=n(r.profit),orders=n(r.orders),margin=round(n(r.margin)),foodCost=round(n(r.food_pct)),labourCost=round(n(r.labour_pct)),prev=n(r.prev_revenue),delta=prev>0?round((revenue-prev)/prev*100):0,targetRevenue=n(r.target_revenue),targetPct=targetRevenue>0?round(revenue/targetRevenue*100):0;return{id:String(r.code),name:String(r.name),city:String(r.city||"Bengaluru"),manager:String(r.manager||"—"),revenue,profit,margin,orders,staff:n(r.staff),aov:orders?round(revenue/orders,0):0,foodCost,labourCost,delta,target:targetPct,state:stateFor({margin,delta,profit,targetPct,foodCost}),cashVariance:n(r.cash_variance),rating:round(n(r.rating),1),inventoryHealth:round(n(r.inventory_health),0),compliance:round(n(r.compliance),0),launched:isoDate(r.opening_date)} as Outlet;});
}

export async function getDailySeries(ctx?:ReportingContext){const c=ctx||await getReportingContext();if(c.dataMode==="demo")return{revenue:demo.dailyRevenue,orders:demo.dailyOrders};const rows=await safe(()=>db()`SELECT EXTRACT(DAY FROM business_date)::int day,COALESCE(sum(net_sales),0)::float8 revenue,COALESCE(sum(orders),0)::int orders FROM daily_sales WHERE EXTRACT(YEAR FROM business_date)=${c.year} AND EXTRACT(MONTH FROM business_date)=${c.month} GROUP BY 1 ORDER BY 1`,[] as any[]);const rev=Array(c.daysInMonth).fill(0),ord=Array(c.daysInMonth).fill(0);for(const r of rows){const i=n(r.day)-1;if(i>=0&&i<rev.length){rev[i]=round(n(r.revenue)/100000,2);ord[i]=n(r.orders);}}return{revenue:rev,orders:ord};}

export async function getChannelMix(ctx?:ReportingContext):Promise<ChannelRow[]>{const c=ctx||await getReportingContext();if(c.dataMode==="demo")return demo.channelMix.map(x=>({...x}));const rows=await safe(()=>db()`SELECT sc.name,COALESCE(sum(cs.net_sales),0)::float8 revenue,COALESCE(sum(cs.orders),0)::int orders,COALESCE(sum(cs.commission),0)::float8 commission FROM channel_sales cs JOIN sales_channels sc ON sc.id=cs.channel_id WHERE EXTRACT(YEAR FROM cs.business_date)=${c.year} AND EXTRACT(MONTH FROM cs.business_date)=${c.month} GROUP BY sc.name ORDER BY revenue DESC`,[] as any[]);const total=rows.reduce((s:any,r:any)=>s+n(r.revenue),0);return rows.map((r:any)=>{const revenue=n(r.revenue),commission=n(r.commission);return{name:String(r.name),share:total?round(revenue/total*100):0,revenue,orders:n(r.orders),commission,contribution:revenue?round((revenue-commission)/revenue*100):0};});}

export async function getExpenseData(ctx?:ReportingContext):Promise<{categories:ExpenseRow[];recent:any[];outletTotals:any[]}>{const c=ctx||await getReportingContext();if(c.dataMode==="demo")return{categories:demo.expenses.map(x=>({...x,status:x.status as any})),recent:[],outletTotals:[]};const rows=await safe(()=>db()`WITH cur AS (SELECT ec.name,ec.code,COALESCE(sum(e.amount),0)::float8 amount FROM expense_categories ec LEFT JOIN expenses e ON e.category_id=ec.id LEFT JOIN reporting_periods p ON p.id=e.period_id AND p.year=${c.year} AND p.month=${c.month} GROUP BY ec.id,ec.name,ec.code), prev AS (SELECT ec.id,COALESCE(sum(e.amount),0)::float8 amount FROM expense_categories ec LEFT JOIN expenses e ON e.category_id=ec.id LEFT JOIN reporting_periods p ON p.id=e.period_id AND (p.year*12+p.month)=(${c.year}*12+${c.month}-1) GROUP BY ec.id), revenue AS (SELECT COALESCE(sum(net_revenue),0)::float8 total FROM outlet_monthly_financials f JOIN reporting_periods p ON p.id=f.period_id WHERE p.year=${c.year} AND p.month=${c.month}) SELECT cur.name,cur.code,cur.amount,COALESCE(prev.amount,0) prev_amount,revenue.total FROM cur CROSS JOIN revenue LEFT JOIN expense_categories ec ON ec.code=cur.code LEFT JOIN prev ON prev.id=ec.id WHERE cur.amount>0 ORDER BY cur.amount DESC`,[] as any[]);const categories=rows.map((r:any)=>{const amount=n(r.amount),total=n(r.total),prev=n(r.prev_amount),pct=total?round(amount/total*100):0,delta=prev?round((amount-prev)/prev*100):0;return{category:String(r.name),amount,pct,delta,status:(delta>8?"watch":delta<0?"ahead":"steady") as ExpenseRow["status"]};});const recent=await safe(()=>db()`SELECT to_char(e.expense_date,'DD Mon') date,o.code outlet,ec.name category,COALESCE(e.vendor_name,'—') vendor,e.amount::float8 amount,COALESCE(e.reference_no,'—') ref FROM expenses e JOIN outlets o ON o.id=e.outlet_id JOIN expense_categories ec ON ec.id=e.category_id ORDER BY e.expense_date DESC,e.created_at DESC LIMIT 8`,[] as any[]);const outletTotals=await safe(()=>db()`SELECT o.code id,o.name,COALESCE(sum(e.amount),0)::float8 total FROM outlets o LEFT JOIN expenses e ON e.outlet_id=o.id LEFT JOIN reporting_periods p ON p.id=e.period_id AND p.year=${c.year} AND p.month=${c.month} WHERE o.status='active' GROUP BY o.id,o.code,o.name ORDER BY total DESC`,[] as any[]);return{categories,recent,outletTotals};}

export async function getCashReconciliation(ctx?:ReportingContext):Promise<CashRow[]>{const c=ctx||await getReportingContext();if(c.dataMode==="demo")return demo.cashReconciliation.map(x=>({...x,status:x.status as CashRow["status"]}));const rows=await safe(()=>db()`SELECT o.code,COALESCE(sum(expected_cash),0)::float8 expected,COALESCE(sum(banked_cash),0)::float8 deposited,COALESCE(sum(variance),0)::float8 variance,count(*) FILTER(WHERE reconciled_at IS NULL) open_count FROM cash_reconciliations cr JOIN outlets o ON o.id=cr.outlet_id WHERE EXTRACT(YEAR FROM business_date)=${c.year} AND EXTRACT(MONTH FROM business_date)=${c.month} GROUP BY o.code ORDER BY o.code`,[] as any[]);return rows.map((r:any)=>{const variance=n(r.variance);return{outlet:String(r.code),expected:n(r.expected),deposited:n(r.deposited),variance,status:Math.abs(variance)>2000?"critical":Math.abs(variance)>1000?"watch":"steady",closed:n(r.open_count)===0};});}

export async function getMonthlyTrend():Promise<MonthlyTrendRow[]>{const ctx=await getReportingContext();if(ctx.dataMode==="demo")return demo.monthlyTrend.map(x=>({...x}));const rows=await safe(()=>db()`SELECT p.year,p.month,COALESCE(sum(f.net_revenue),0)::float8 revenue,COALESCE(sum(f.net_profit),0)::float8 profit FROM reporting_periods p LEFT JOIN outlet_monthly_financials f ON f.period_id=p.id GROUP BY p.id,p.year,p.month ORDER BY p.year DESC,p.month DESC LIMIT 6`,[] as any[]);return rows.reverse().map((r:any)=>{const revenue=n(r.revenue),profit=n(r.profit);return{month:monthFmt.format(new Date(Date.UTC(n(r.year),n(r.month)-1,2))).toUpperCase(),revenue:round(revenue/100000),profit:round(profit/100000),margin:revenue?round(profit/revenue*100):0};});}

export async function getInventoryRisks():Promise<InventoryRiskRow[]>{const ctx=await getReportingContext();if(ctx.dataMode==="demo")return demo.inventoryRisks.map(x=>({...x}));const rows=await safe(()=>db()`WITH latest AS (SELECT DISTINCT ON(s.outlet_id,s.item_id) s.outlet_id,s.item_id,s.on_hand_qty::float8 qty,s.unit_cost::float8 unit_cost,COALESCE(s.reorder_point,0)::float8 reorder_point,s.wastage_qty::float8 wastage FROM inventory_snapshots s ORDER BY s.outlet_id,s.item_id,s.snapshot_date DESC) SELECT i.sku,i.name,i.category,count(*) FILTER(WHERE l.reorder_point>0 AND l.qty<l.reorder_point)::int low_outlets,COALESCE(sum(l.qty*l.unit_cost),0)::float8 stock_value,COALESCE(sum(l.wastage*l.unit_cost),0)::float8 wastage_value,COALESCE(avg(CASE WHEN l.reorder_point>0 THEN l.qty/l.reorder_point ELSE 3 END),3)::float8 cover_ratio FROM latest l JOIN inventory_items i ON i.id=l.item_id GROUP BY i.id,i.sku,i.name,i.category ORDER BY low_outlets DESC,stock_value DESC LIMIT 12`,[] as any[]);return rows.map((r:any)=>{const ratio=n(r.cover_ratio),days=round(Math.max(.1,ratio*2),1),low=n(r.low_outlets);return{item:String(r.name),sku:String(r.sku||"—"),category:String(r.category||"Other"),outlets:low,days,variance:n(r.stock_value)?round(n(r.wastage_value)/n(r.stock_value)*100):0,stockValue:n(r.stock_value),action:low>0?"Replenish":days<3?"Monitor":"Healthy"};});}

export async function getVendors(ctx?:ReportingContext):Promise<VendorRow[]>{const c=ctx||await getReportingContext();if(c.dataMode==="demo")return demo.vendors.map(x=>({...x,status:x.status as VendorRow["status"]}));const rows=await safe(()=>db()`WITH cur AS (SELECT v.id,v.code,v.name,v.payment_terms,COALESCE(v.category,'General') category,COALESCE(v.reliability_pct,0)::float8 reliability,COALESCE(v.fill_rate_pct,0)::float8 fill_rate,COALESCE(sum(p.total) FILTER(WHERE EXTRACT(YEAR FROM p.purchase_date)=${c.year} AND EXTRACT(MONTH FROM p.purchase_date)=${c.month}),0)::float8 spend,COALESCE(sum(p.total) FILTER(WHERE (EXTRACT(YEAR FROM p.purchase_date)::int*12+EXTRACT(MONTH FROM p.purchase_date)::int)=(${c.year}*12+${c.month}-1)),0)::float8 prev_spend FROM vendors v LEFT JOIN purchases p ON p.vendor_id=v.id WHERE v.active GROUP BY v.id) SELECT * FROM cur ORDER BY spend DESC,name`,[] as any[]);return rows.map((r:any)=>{const spend=n(r.spend),prev=n(r.prev_spend),change=prev?round((spend-prev)/prev*100):0,reliability=n(r.reliability),fillRate=n(r.fill_rate);return{id:String(r.code||String(r.id).slice(0,6)),name:String(r.name),category:String(r.category||"General"),spend,change,reliability,fillRate,terms:String(r.payment_terms||"—"),status:(fillRate&&fillRate<90?"watch":change<0?"ahead":"steady") as VendorRow["status"]};});}

export async function getMenuData(ctx?:ReportingContext):Promise<{items:MenuItemRow[];categories:MenuCategoryRow[]}>{const c=ctx||await getReportingContext();if(c.dataMode==="demo")return{items:demo.menuItems.map(x=>({...x,state:x.state as OutletState})),categories:demo.menuCategories.map(x=>({...x}))};const rows=await safe(()=>db()`SELECT m.sku,m.name,COALESCE(m.category,'Other') category,sum(mp.quantity_sold)::int units,COALESCE(sum(mp.net_sales),0)::float8 revenue,COALESCE(sum(mp.estimated_food_cost),0)::float8 food_cost,COALESCE(sum(mp.contribution_margin),0)::float8 contribution FROM menu_performance_monthly mp JOIN menu_items m ON m.id=mp.menu_item_id JOIN reporting_periods p ON p.id=mp.period_id WHERE p.year=${c.year} AND p.month=${c.month} GROUP BY m.id,m.sku,m.name,m.category ORDER BY revenue DESC`,[] as any[]);const total=rows.reduce((s:any,r:any)=>s+n(r.revenue),0);const items=rows.map((r:any,i:number)=>{const revenue=n(r.revenue),food=n(r.food_cost),contribution=n(r.contribution),foodCost=revenue?round(food/revenue*100):0,contributionPct=revenue?round(contribution/revenue*100):0;return{code:String(r.sku||`ITEM-${i+1}`),name:String(r.name),category:String(r.category),units:n(r.units),revenue,foodCost,contribution:contributionPct,delta:0,rank:i+1,state:contributionPct<25?"critical":contributionPct<35?"watch":contributionPct>45?"ahead":"steady" as OutletState};});const cats=new Map<string,{sales:number;units:number;contribution:number}>();for(const it of items){const x=cats.get(it.category)||{sales:0,units:0,contribution:0};x.sales+=it.revenue;x.units+=it.units;x.contribution+=it.revenue*it.contribution/100;cats.set(it.category,x);}const categories=[...cats.entries()].map(([name,x])=>({name,sales:x.sales,units:x.units,mix:total?round(x.sales/total*100):0,margin:x.sales?round(x.contribution/x.sales*100):0,delta:0})).sort((a,b)=>b.sales-a.sales);return{items,categories};}

export async function getTasks():Promise<TaskRow[]>{const c=await getReportingContext();if(c.dataMode==="demo")return demo.tasks.map(x=>({...x}));const rows=await safe(()=>db()`SELECT t.id::text,t.title,COALESCE(o.code,'GROUP') outlet,COALESCE(u.display_name,'Owner') owner,to_char(t.due_at AT TIME ZONE 'Asia/Kolkata','DD Mon') due,t.priority,t.status,COALESCE(a.alert_type,'—') linked FROM tasks t LEFT JOIN outlets o ON o.id=t.outlet_id LEFT JOIN app_users u ON u.id=t.assigned_user_id LEFT JOIN alerts a ON a.id=t.alert_id WHERE t.status NOT IN ('done','cancelled') ORDER BY CASE t.priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,t.due_at NULLS LAST LIMIT 100`,[] as any[]);return rows.map((r:any)=>({...r,id:String(r.id),title:String(r.title),outlet:String(r.outlet),owner:String(r.owner),due:String(r.due||"—"),priority:String(r.priority),status:String(r.status).replaceAll("_"," "),linked:String(r.linked)}));}

export async function getDocuments():Promise<DocumentRow[]>{const c=await getReportingContext();if(c.dataMode==="demo")return demo.documents.map(x=>({...x}));const rows=await safe(()=>db()`SELECT d.id::text,d.title name,d.document_type type,COALESCE(o.code,'GROUP') scope,COALESCE(u.display_name,'Owner') owner,to_char(d.created_at AT TIME ZONE 'Asia/Kolkata','DD Mon YYYY') updated,d.expires_on FROM documents d LEFT JOIN outlets o ON o.id=d.outlet_id LEFT JOIN app_users u ON u.id=d.uploaded_by ORDER BY d.created_at DESC LIMIT 100`,[] as any[]);const today=currentIstParts();const todayDate=new Date(Date.UTC(today.year,today.month-1,today.day));return rows.map((r:any)=>{let status="Valid";if(r.expires_on){const d=new Date(String(r.expires_on));const days=Math.ceil((d.getTime()-todayDate.getTime())/86400000);status=days<0?"Expired":days<=30?`Review in ${days}d`:"Valid";}return{id:String(r.id),name:String(r.name),type:String(r.type),scope:String(r.scope),owner:String(r.owner),updated:String(r.updated),status};});}

export async function getImportHistory():Promise<ImportHistoryRow[]>{const c=await getReportingContext();if(c.dataMode==="demo")return demo.importHistory.map(x=>({...x}));const rows=await safe(()=>db()`SELECT original_filename file,import_type type,COALESCE(row_count,0) rows,COALESCE(accepted_count,0) accepted,COALESCE(rejected_count,0) rejected,status,to_char(created_at AT TIME ZONE 'Asia/Kolkata','DD Mon · HH24:MI') at FROM data_import_jobs ORDER BY created_at DESC LIMIT 50`,[] as any[]);return rows.map((r:any)=>({file:String(r.file),type:String(r.type).replaceAll("_"," "),rows:n(r.rows),accepted:n(r.accepted),rejected:n(r.rejected),status:String(r.status).replaceAll("_"," "),at:String(r.at)}));}

export async function getActivity():Promise<ActivityRow[]>{const c=await getReportingContext();if(c.dataMode==="demo")return demo.activity.map(x=>({...x}));const rows=await safe(()=>db()`SELECT to_char(a.created_at AT TIME ZONE 'Asia/Kolkata','HH24:MI') time,COALESCE(u.display_name,'System') actor,a.action,COALESCE(o.code,a.entity_type) target,a.entity_type type FROM audit_log a LEFT JOIN app_users u ON u.id=a.actor_user_id LEFT JOIN outlets o ON o.id=a.outlet_id ORDER BY a.created_at DESC LIMIT 20`,[] as any[]);return rows.map((r:any)=>({time:String(r.time),actor:String(r.actor),action:String(r.action).replaceAll("_"," "),target:String(r.target||"GROUP"),type:String(r.type)}));}

export async function getAlerts():Promise<AlertRow[]>{const c=await getReportingContext();if(c.dataMode==="demo")return demo.alerts.map(x=>({...x}));const rows=await safe(()=>db()`SELECT a.id::text,a.severity,COALESCE(o.code,'GROUP') outlet,a.title,COALESCE(a.detail,'') detail,CASE WHEN now()-a.detected_at<interval '1 hour' THEN floor(extract(epoch from(now()-a.detected_at))/60)::int||'m' WHEN now()-a.detected_at<interval '1 day' THEN floor(extract(epoch from(now()-a.detected_at))/3600)::int||'h' ELSE floor(extract(epoch from(now()-a.detected_at))/86400)::int||'d' END age,'Owner' owner FROM alerts a LEFT JOIN outlets o ON o.id=a.outlet_id WHERE a.status IN ('open','acknowledged') ORDER BY CASE a.severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'watch' THEN 2 ELSE 3 END,a.detected_at DESC LIMIT 100`,[] as any[]);return rows.map((r:any)=>({id:String(r.id),severity:String(r.severity),outlet:String(r.outlet),title:String(r.title),detail:String(r.detail),age:String(r.age),owner:"Owner"}));}


async function getPreviousOverviewMetrics(c:ReportingContext){
 const prevMonth=c.month===1?12:c.month-1,prevYear=c.month===1?c.year-1:c.year;
 const label=labelFor(prevYear,prevMonth);
 if(c.dataMode!=="live")return{label,hasData:false,revenue:0,profit:0,margin:0,orders:0,aov:0,grossProfit:0,operatingProfit:0,dailyRevenue:[] as number[]};
 const [agg,dailyRows]=await Promise.all([
  safe(()=>db()`SELECT count(f.id)::int records,COALESCE(sum(f.net_revenue),0)::float8 revenue,COALESCE(sum(f.net_profit),0)::float8 profit,COALESCE(sum(f.total_orders),0)::int orders,COALESCE(sum(f.gross_profit),0)::float8 gross_profit,COALESCE(sum(f.operating_profit),0)::float8 operating_profit FROM reporting_periods p LEFT JOIN outlet_monthly_financials f ON f.period_id=p.id WHERE p.year=${prevYear} AND p.month=${prevMonth}`,[] as any[]),
  safe(()=>db()`SELECT EXTRACT(DAY FROM business_date)::int day,COALESCE(sum(net_sales),0)::float8 revenue FROM daily_sales WHERE EXTRACT(YEAR FROM business_date)=${prevYear} AND EXTRACT(MONTH FROM business_date)=${prevMonth} GROUP BY 1 ORDER BY 1`,[] as any[])
 ]);
 const r=agg[0]||{},revenue=n(r.revenue),profit=n(r.profit),orders=n(r.orders),days=new Date(Date.UTC(prevYear,prevMonth,0)).getUTCDate(),dailyRevenue=Array(days).fill(0);
 for(const d of dailyRows){const i=n(d.day)-1;if(i>=0&&i<dailyRevenue.length)dailyRevenue[i]=round(n(d.revenue)/100000,2);}
 const hasData=n(r.records)>0||dailyRows.length>0;
 return{label,hasData,revenue,profit,margin:revenue?profit/revenue*100:0,orders,aov:orders?revenue/orders:0,grossProfit:n(r.gross_profit),operatingProfit:n(r.operating_profit),dailyRevenue};
}
export async function getOverviewData(){const ctx=await getReportingContext();const [outlets,daily,channelMix,alerts,activity,previous]=await Promise.all([getOutlets(ctx),getDailySeries(ctx),getChannelMix(ctx),getAlerts(),getActivity(),getPreviousOverviewMetrics(ctx)]);const targetRows=ctx.dataMode==="live"?await safe(()=>db()`SELECT COALESCE(sum(COALESCE(t.revenue_target,o.monthly_revenue_target,0)),0)::float8 target FROM outlets o LEFT JOIN reporting_periods p ON p.year=${ctx.year} AND p.month=${ctx.month} LEFT JOIN outlet_targets t ON t.outlet_id=o.id AND t.period_id=p.id WHERE o.status='active'`,[] as any[]):[];const fin=ctx.dataMode==="live"?await safe(()=>db()`SELECT COALESCE(sum(gross_profit),0)::float8 gross_profit,COALESCE(sum(operating_profit),0)::float8 operating_profit FROM outlet_monthly_financials f JOIN reporting_periods p ON p.id=f.period_id WHERE p.year=${ctx.year} AND p.month=${ctx.month}`,[] as any[]):[];const groupTarget=n(targetRows[0]?.target)|| (ctx.dataMode==="demo"?16_400_000:0);return{reportingPeriod:ctx,outlets,dailyRevenue:daily.revenue,channelMix,alerts,activity,groupTarget,grossProfit:n(fin[0]?.gross_profit)||(ctx.dataMode==="demo"?4_065_320:0),operatingProfit:n(fin[0]?.operating_profit)||(ctx.dataMode==="demo"?2_148_760:0),previous};}

export async function getFinancialData(){const ctx=await getReportingContext();const [outlets,expenses,channelMix,cashReconciliation,monthlyTrend]=await Promise.all([getOutlets(ctx),getExpenseData(ctx),getChannelMix(ctx),getCashReconciliation(ctx),getMonthlyTrend()]);const financial=ctx.dataMode==="live"?await safe(()=>db()`SELECT COALESCE(sum(gross_profit),0)::float8 gross_profit,COALESCE(sum(operating_profit),0)::float8 operating_profit,COALESCE(sum(net_profit),0)::float8 net_profit,COALESCE(sum(net_revenue),0)::float8 revenue FROM outlet_monthly_financials f JOIN reporting_periods p ON p.id=f.period_id WHERE p.year=${ctx.year} AND p.month=${ctx.month}`,[] as any[]):[];return{ctx,outlets,expenses:expenses.categories,channelMix,cashReconciliation,monthlyTrend,grossProfit:n(financial[0]?.gross_profit)||(ctx.dataMode==="demo"?4_065_320:0),operatingProfit:n(financial[0]?.operating_profit)||(ctx.dataMode==="demo"?2_148_760:0)};}

export async function getSalesData(){const ctx=await getReportingContext();const [outlets,daily,channelMix]=await Promise.all([getOutlets(ctx),getDailySeries(ctx),getChannelMix(ctx)]);return{ctx,outlets,dailyRevenue:daily.revenue,dailyOrders:daily.orders,channelMix};}

export async function getProcurementData(){const ctx=await getReportingContext();const vendors=await getVendors(ctx);const payables=ctx.dataMode==="live"?await safe(()=>db()`SELECT count(*) FILTER(WHERE payment_status IN ('pending','partial'))::int invoices,COALESCE(sum(total) FILTER(WHERE payment_status IN ('pending','partial')),0)::float8 open,COALESCE(sum(total) FILTER(WHERE payment_status='disputed'),0)::float8 disputed FROM purchases`,[] as any[]):[];return{ctx,vendors,payables:{invoices:n(payables[0]?.invoices),open:n(payables[0]?.open),disputed:n(payables[0]?.disputed)}};}

export async function getReportsData(){const ctx=await getReportingContext();const trend=await getMonthlyTrend();const imports=await getImportHistory();return{ctx,trend,imports};}

export async function getSettingsOutlets(){return await getOutlets();}

export { demo };

export async function getOutletDetailData(code:string){const ctx=await getReportingContext();const outlets=await getOutlets(ctx);const outlet=outlets.find(o=>o.id.toUpperCase()===code.toUpperCase())||null;if(!outlet)return{ctx,outlets,outlet:null,dailyRevenue:[] as number[],cash:null as CashRow|null};if(ctx.dataMode==="demo")return{ctx,outlets,outlet,dailyRevenue:demo.dailyRevenue,cash:demo.cashReconciliation.find(c=>c.outlet===outlet.id)||null};const rows=await safe(()=>db()`SELECT EXTRACT(DAY FROM ds.business_date)::int day,COALESCE(sum(ds.net_sales),0)::float8 revenue FROM daily_sales ds JOIN outlets o ON o.id=ds.outlet_id WHERE upper(o.code)=upper(${code}) AND EXTRACT(YEAR FROM ds.business_date)=${ctx.year} AND EXTRACT(MONTH FROM ds.business_date)=${ctx.month} GROUP BY 1 ORDER BY 1`,[] as any[]);const dailyRevenue=Array(ctx.daysInMonth).fill(0);for(const r of rows){const i=n(r.day)-1;if(i>=0&&i<dailyRevenue.length)dailyRevenue[i]=round(n(r.revenue)/100000,2);}const cash=(await getCashReconciliation(ctx)).find(c=>c.outlet===outlet.id)||null;return{ctx,outlets,outlet,dailyRevenue,cash};}
