import { compactMoney } from "@/lib/demo-data";
import { Delta, Donut, PageLead, Panel, RevenueLine, SectionHead, SparkBars } from "@/components/ui";
import { getSalesData } from "@/lib/command-data";
export default async function SalesPage(){
 const {ctx,outlets,dailyRevenue,dailyOrders,channelMix}=await getSalesData();const compare=dailyRevenue.map((v,i)=>v*(.89+(i%4)*.01));const totalOrders=outlets.reduce((s,o)=>s+o.orders,0),totalRevenue=outlets.reduce((s,o)=>s+o.revenue,0);const aov=totalOrders?Math.round(totalRevenue/totalOrders):0;const direct=channelMix.filter(c=>["Dine-in","Takeaway","Direct"].includes(c.name)).reduce((s,c)=>s+c.share,0);const agg=channelMix.filter(c=>["Swiggy","Zomato"].includes(c.name)).reduce((s,c)=>s+c.share,0);const best=Math.max(0,...dailyRevenue),low=Math.min(...dailyRevenue.filter(v=>v>0));
 return <><PageLead code="04" eyebrow={`SALES INTELLIGENCE / DEMAND / ${ctx.label}`} title="See where revenue is actually coming from." copy="Track daily velocity, channel economics, outlet mix and demand concentration before they become month-end surprises." action={<a className="command-button" href="/imports">IMPORT SALES FILE <span>→</span></a>} meta={<><span>{totalOrders.toLocaleString("en-IN")} ORDERS</span><span>₹{aov} GROUP AOV</span><span>{ctx.daysInMonth} BUSINESS DAYS</span></>}/>
 <div className="sales-kpis"><div><span>MTD REVENUE</span><strong>{compactMoney(totalRevenue)}</strong><small>{ctx.dataMode.toUpperCase()}</small></div><div><span>ORDERS</span><strong>{totalOrders.toLocaleString("en-IN")}</strong><small>MTD</small></div><div><span>GROUP AOV</span><strong>₹{aov}</strong><small>NET REVENUE / ORDERS</small></div><div><span>DIRECT MIX</span><strong>{direct.toFixed(1)}%</strong><small>DINE-IN + TAKEAWAY + DIRECT</small></div><div><span>AGGREGATOR MIX</span><strong>{agg.toFixed(1)}%</strong><small>SWIGGY + ZOMATO</small></div></div>
 <div className="sales-grid command-gap"><Panel className="sales-main"><SectionHead no="01" kicker="DAILY VELOCITY" title="Group revenue by business day"/><div className="sales-chart"><RevenueLine values={dailyRevenue} compare={compare}/></div><div className="chart-labels"><span>01</span><span>07</span><span>14</span><span>21</span><span>28</span><span>{ctx.daysInMonth}</span></div><div className="sales-foot-stats"><span><b>₹{best.toFixed(1)}L</b><small>BEST DAY</small></span><span><b>₹{Number.isFinite(low)?low.toFixed(1):"0.0"}L</b><small>LOWEST DAY</small></span><span><b>₹{(dailyRevenue.reduce((s,v)=>s+v,0)/Math.max(1,dailyRevenue.filter(v=>v>0).length)).toFixed(1)}L</b><small>AVG / LOADED DAY</small></span><span><b>{dailyOrders.reduce((s,v)=>s+v,0).toLocaleString("en-IN")}</b><small>DAILY IMPORT ORDERS</small></span></div></Panel>
 <Panel className="sales-channel"><SectionHead no="02" kicker="CHANNEL MIX" title="Where orders originate"/><Donut center={compactMoney(channelMix.reduce((s,c)=>s+c.revenue,0))} sub="MONTH TO DATE" segments={channelMix.map((c,i)=>({value:c.share,className:`seg-${i+1}`}))}/><div className="channel-list compact">{channelMix.map((c,i)=><div key={c.name}><i className={`dot dot-${i+1}`}/><span><strong>{c.name}</strong><small>{compactMoney(c.revenue)} · {c.orders.toLocaleString("en-IN")} orders</small></span><b>{c.share}%</b></div>)}</div></Panel>
 <Panel className="sales-outlets"><SectionHead no="03" kicker="OUTLET DEMAND" title="Revenue velocity by location"/><div className="sales-outlet-list">{[...outlets].sort((a,b)=>b.revenue-a.revenue).map((o,i)=><div key={o.id}><b>{String(i+1).padStart(2,"0")}</b><span><strong>{o.name}</strong><small>{o.orders.toLocaleString("en-IN")} orders · ₹{o.aov} AOV</small></span><em>{compactMoney(o.revenue)}</em><Delta value={o.delta}/></div>)}</div></Panel>
 <Panel className="sales-contribution"><SectionHead no="04" kicker="CHANNEL CONTRIBUTION" title="After commission pressure"/><div className="contribution-bars">{channelMix.map(c=><div key={c.name}><span>{c.name}</span><i><b style={{width:`${Math.min(100,c.contribution)}%`}}/></i><strong>{c.contribution}%</strong><small>{compactMoney(c.commission)} commission</small></div>)}</div></Panel></div></>;
}
