import { compactMoney } from "@/lib/demo-data";
import { Delta, Meter, PageLead, Panel, SectionHead, StatePill } from "@/components/ui";
import { getMenuData,getReportingContext } from "@/lib/command-data";
export default async function MenuPage(){const ctx=await getReportingContext();const {items:menuItems,categories:menuCategories}=await getMenuData(ctx);const sales=menuItems.reduce((s,i)=>s+i.revenue,0),units=menuItems.reduce((s,i)=>s+i.units,0);return <>
<PageLead code="05" eyebrow={`MENU INTELLIGENCE / PRODUCT ECONOMICS / ${ctx.label}`} title="Know what sells. Know what actually earns." copy="Track menu sales, estimated food cost and contribution by item and category from imported outlet performance data." action={<a className="command-button" href="/imports">IMPORT MENU PERFORMANCE <span>→</span></a>} meta={<><span>{menuItems.length} TRACKED ITEMS</span><span>{units.toLocaleString("en-IN")} UNITS</span><span>{compactMoney(sales)} SALES</span></>}/>
<div className="menu-kpis"><div><span>MENU SALES</span><strong>{compactMoney(sales)}</strong><small>IMPORTED PERFORMANCE</small></div><div><span>UNITS SOLD</span><strong>{units.toLocaleString("en-IN")}</strong><small>MTD</small></div><div><span>CATEGORIES</span><strong>{menuCategories.length}</strong><small>ACTIVE MIX</small></div><div><span>LOW CONTRIBUTION</span><strong>{menuItems.filter(i=>i.contribution<35).length}</strong><small>&lt;35%</small></div><div><span>HIGH FOOD COST</span><strong>{menuItems.filter(i=>i.foodCost>38).length}</strong><small>&gt;38%</small></div></div>
<div className="menu-grid command-gap"><Panel className="menu-rank"><SectionHead no="01" kicker="ITEM PERFORMANCE" title="Menu contribution board"/><div className="menu-table"><div className="menu-head"><span>ITEM</span><span>UNITS</span><span>SALES</span><span>FOOD COST</span><span>CONTRIBUTION</span><span>STATE</span></div>{menuItems.map(i=><div className="menu-row" key={i.code}><span><b>{String(i.rank).padStart(2,"0")}</b><strong>{i.name}</strong><small>{i.code} · {i.category}</small></span><em>{i.units.toLocaleString("en-IN")}</em><em>{compactMoney(i.revenue)}</em><strong className={i.foodCost>38?"bad-text":""}>{i.foodCost.toFixed(1)}%</strong><strong className={i.contribution<35?"bad-text":""}>{i.contribution.toFixed(1)}%</strong><StatePill state={i.state}>{i.state.toUpperCase()}</StatePill></div>)}</div></Panel>
<Panel className="menu-category"><SectionHead no="02" kicker="CATEGORY MIX" title="Where menu revenue sits"/><div className="category-stack">{menuCategories.map((c,i)=><div key={c.name}><span><b>{String(i+1).padStart(2,"0")}</b><strong>{c.name}</strong><small>{c.units.toLocaleString("en-IN")} units</small></span><em>{compactMoney(c.sales)}</em><Meter value={c.mix*2} tone={c.margin<35?"red":"teal"}/><strong>{c.mix.toFixed(1)}%</strong><small>{c.margin.toFixed(1)}% contribution</small></div>)}</div></Panel>
<Panel className="menu-watch"><SectionHead no="03" kicker="CONTROL WATCH" title="Items requiring review"/><div className="anomaly-list">{menuItems.filter(i=>i.foodCost>38||i.contribution<35).map((i,idx)=><div className="is-critical" key={i.code}><b>{String(idx+1).padStart(2,"0")}</b><span><strong>{i.name}</strong><small>{i.foodCost.toFixed(1)}% food cost · {i.contribution.toFixed(1)}% contribution</small></span><em>REVIEW</em></div>)}{!menuItems.some(i=>i.foodCost>38||i.contribution<35)&&<p>No menu items currently cross the configured review bands.</p>}</div></Panel>
<Panel className="menu-trend" tone="cream"><SectionHead no="04" kicker="CATEGORY MOMENTUM" title="Contribution structure"/><div className="price-watch">{menuCategories.slice(0,5).map((c,i)=><div key={c.name}><span><b>M{String(i+1).padStart(2,"0")}</b>{c.name}</span><strong>{c.margin.toFixed(1)}%</strong><small>CONTRIBUTION</small></div>)}</div></Panel></div></>}
