import { compactMoney } from "@/lib/demo-data";
import { Delta, Meter, PageLead, Panel, SectionHead, StatePill } from "@/components/ui";
import { ExpenseEntryControl } from "@/components/qa-record-actions";
import { getExpenseData,getOutlets,getReportingContext } from "@/lib/command-data";
import { expenseCategoryOptions,outletOptions } from "@/lib/restaurant-controls";
export default async function ExpensesPage(){const ctx=await getReportingContext();const [{categories:expenses,recent,outletTotals},outlets,outletRecords,categories]=await Promise.all([getExpenseData(ctx),getOutlets(ctx),outletOptions(),expenseCategoryOptions()]);const revenue=outlets.reduce((s,o)=>s+o.revenue,0),total=expenses.reduce((s,e)=>s+e.amount,0);const map=new Map(outletTotals.map((x:any)=>[String(x.id),Number(x.total)]));const outletExpense=outlets.map(o=>{const value=map.get(o.id)||0;const pct=o.revenue?value/o.revenue*100:0;return{id:o.id,name:o.name,total:value,pct,delta:0,state:(pct>60?"critical":pct>55?"watch":"steady") as "critical"|"watch"|"steady"};});return <>
<PageLead code="09" eyebrow={`EXPENSE CONTROL / COST BASE / ${ctx.label}`} title="Every rupee should have a reason." copy="Monitor recurring costs, outlet expense intensity and vendor-linked spend before they distort the monthly close." action={<a className="command-button" href="#expense-entry">ADD EXPENSE <span>→</span></a>}/>
<div className="expense-kpis"><div><span>TRACKED EXPENSES</span><strong>{compactMoney(total)}</strong><small>MONTH TO DATE</small></div><div><span>EXPENSE / SALES</span><strong>{revenue?(total/revenue*100).toFixed(1):"0.0"}%</strong><small>ITEMISED LEDGER</small></div><div><span>CATEGORIES</span><strong>{expenses.length}</strong><small>WITH MTD ACTIVITY</small></div><div><span>WATCH CATEGORIES</span><strong>{expenses.filter(e=>e.status==='watch').length}</strong><small>RISING VS PRIOR MONTH</small></div><div><span>RECENT POSTS</span><strong>{recent.length}</strong><small>VISIBLE LEDGER</small></div></div>
<div className="expense-grid command-gap"><Panel className="expense-category"><SectionHead no="01" kicker="CATEGORY CONTROL" title="Cost base by category"/><div className="expense-category-rows">{expenses.map((e,i)=><div key={e.category}><b>E{String(i+1).padStart(2,"0")}</b><span><strong>{e.category}</strong><small>{e.pct.toFixed(1)}% of sales</small></span><Meter value={Math.min(100,e.pct*2.7)} tone={e.status==='watch'?"red":"teal"}/><em>{compactMoney(e.amount)}</em><Delta value={e.delta}/></div>)}</div></Panel>
<Panel className="expense-outlets"><SectionHead no="02" kicker="OUTLET INTENSITY" title="Expense load by location"/><div className="expense-outlet-grid">{outletExpense.map(o=><div key={o.id} className={`expense-outlet state-${o.state}`}><span><b>{o.id}</b><StatePill state={o.state}>{o.state.toUpperCase()}</StatePill></span><strong>{o.name}</strong><em>{compactMoney(o.total)}</em><small>{o.pct.toFixed(1)}% of outlet revenue</small></div>)}</div></Panel>
<Panel className="expense-recent"><SectionHead no="03" kicker="RECENT LEDGER" title="Latest posted expenses"/><div className="ledger-table"><div className="ledger-head"><span>DATE</span><span>OUTLET</span><span>CATEGORY</span><span>REFERENCE</span><span>AMOUNT</span></div>{recent.map((r:any,i:number)=><div className="ledger-row" key={`${r.ref}-${i}`}><time>{String(r.date)}</time><b>{String(r.outlet)}</b><span><strong>{String(r.category)}</strong><small>{String(r.vendor)}</small></span><code>{String(r.ref)}</code><em>{compactMoney(Number(r.amount))}</em></div>)}</div></Panel>
<Panel className="expense-anomalies" tone="cream"><SectionHead no="04" kicker="VARIANCE DETECTOR" title="Expense movements worth checking"/><div className="anomaly-list">{expenses.filter(e=>Math.abs(e.delta)>=8).slice(0,5).map((e,i)=><div className={e.delta>0?"is-critical":""} key={e.category}><b>{String(i+1).padStart(2,"0")}</b><span><strong>{e.category}</strong><small>{e.delta>0?"Increase":"Decrease"} vs previous month</small></span><em>{e.delta>0?"REVIEW":"SAVING"}</em></div>)}{!expenses.some(e=>Math.abs(e.delta)>=8)&&<p>No material expense movements currently cross the review threshold.</p>}</div></Panel></div>
<ExpenseEntryControl outlets={outletRecords as any} categories={categories as any} year={ctx.year} month={ctx.month}/>
<div className="page-secondary-action"><a className="command-button" href="/imports">IMPORT EXPENSE CSV <span>→</span></a></div>
</>}
