import { z } from "zod";
import { requireApiProfile } from "@/lib/access-control";
import { db } from "@/lib/db";
import { enforceSameOrigin,readJsonWithLimit,requestParseError,consumeRateLimit,rateLimitResponse } from "@/lib/http-security";
import { hasFreshFinancialMfa } from "@/lib/mfa";
import { ensurePeriod } from "@/lib/restaurant-controls";
const nullableRating=z.union([z.number().min(0).max(5),z.null()]);
const schema=z.object({outletId:z.string().uuid(),year:z.number().int().min(2020).max(2100),month:z.number().int().min(1).max(12),googleRating:nullableRating,swiggyRating:nullableRating,zomatoRating:nullableRating,complaintsReceived:z.number().int().min(0).max(100000),complaintsUnresolved:z.number().int().min(0).max(100000),ownerNotes:z.string().trim().max(2000).optional()}).refine(v=>v.complaintsUnresolved<=v.complaintsReceived,{message:"Unresolved complaints cannot exceed complaints received",path:["complaintsUnresolved"]});
export async function GET(){const access=await requireApiProfile("/api/customer-experience");if("response" in access)return access.response;const rows=await db()`SELECT c.id,c.outlet_id,o.code outlet_code,o.name outlet_name,p.year,p.month,c.google_rating,c.swiggy_rating,c.zomato_rating,c.complaints_received,c.complaints_unresolved,c.owner_notes FROM customer_experience_monthly c JOIN outlets o ON o.id=c.outlet_id JOIN reporting_periods p ON p.id=c.period_id ORDER BY p.year DESC,p.month DESC,o.name`;return Response.json({rows},{headers:{"Cache-Control":"private, no-store, max-age=0"}})}
export async function POST(req:Request){const same=enforceSameOrigin(req);if(same)return same;const access=await requireApiProfile("/api/customer-experience");if("response" in access)return access.response;if(!(await hasFreshFinancialMfa()))return Response.json({error:"Fresh MFA required",code:"MFA_FRESH_REQUIRED"},{status:428});const lim=await consumeRateLimit("customer-experience-write",20,60,"user");if(!lim.allowed)return rateLimitResponse(lim.retryAfter);try{const parsed=schema.safeParse(await readJsonWithLimit(req,16000));if(!parsed.success)return Response.json({error:"Invalid customer experience record",issues:parsed.error.flatten()},{status:400});const v=parsed.data;const period=await ensurePeriod(v.year,v.month);if(period.status==="closed")return Response.json({error:"Reporting period is closed"},{status:409});await db()`INSERT INTO customer_experience_monthly(outlet_id,period_id,google_rating,swiggy_rating,zomato_rating,complaints_received,complaints_unresolved,owner_notes) VALUES(${v.outletId},${period.id},${v.googleRating},${v.swiggyRating},${v.zomatoRating},${v.complaintsReceived},${v.complaintsUnresolved},${v.ownerNotes||null}) ON CONFLICT(outlet_id,period_id) DO UPDATE SET google_rating=EXCLUDED.google_rating,swiggy_rating=EXCLUDED.swiggy_rating,zomato_rating=EXCLUDED.zomato_rating,complaints_received=EXCLUDED.complaints_received,complaints_unresolved=EXCLUDED.complaints_unresolved,owner_notes=EXCLUDED.owner_notes,updated_at=NOW()`;const ratings=[v.googleRating,v.swiggyRating,v.zomatoRating].filter((x):x is number=>x!==null);const avg=ratings.length?ratings.reduce((a,b)=>a+b,0)/ratings.length:null;await db()`UPDATE alerts SET status='resolved',resolved_by=${access.profile.id},resolved_at=NOW() WHERE outlet_id=${v.outletId} AND alert_type='customer_experience' AND status IN ('open','acknowledged')`;if((avg!==null&&avg<4.1)||v.complaintsUnresolved>=3){await db()`INSERT INTO alerts(outlet_id,alert_type,severity,title,detail,metadata) VALUES(${v.outletId},'customer_experience',${v.complaintsUnresolved>=5?'high':'watch'},'Customer experience requires attention',${`Average rating ${avg===null?'n/a':avg.toFixed(2)} / 5 · ${v.complaintsUnresolved} unresolved complaints`},${JSON.stringify({year:v.year,month:v.month,averageRating:avg,unresolved:v.complaintsUnresolved})}::jsonb)`;}return Response.json({ok:true},{headers:{"Cache-Control":"private, no-store, max-age=0"}})}catch(error){const r=requestParseError(error);if(r)return r;throw error;}}
