"use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";

type Outlet={id:string;code:string;name:string};
type Row={id:string;outlet_id:string;outlet_code:string;outlet_name:string;year:number;month:number;google_rating:number|null;swiggy_rating:number|null;zomato_rating:number|null;complaints_received:number;complaints_unresolved:number;owner_notes?:string|null};
export function CustomerExperienceControl({outlets,rows,year,month}:{outlets:Outlet[];rows:Row[];year:number;month:number}){
 const router=useRouter();const currentRows=useMemo(()=>rows.filter(r=>Number(r.year)===year&&Number(r.month)===month),[rows,year,month]);
 const [form,setForm]=useState({outletId:outlets[0]?.id||"",year,month,googleRating:4.5,swiggyRating:4.4,zomatoRating:4.3,complaintsReceived:0,complaintsUnresolved:0,ownerNotes:""});const [message,setMessage]=useState("");
 const avg=(r:Row)=>{const v=[r.google_rating,r.swiggy_rating,r.zomato_rating].filter(x=>x!=null).map(Number);return v.length?v.reduce((a,b)=>a+b,0)/v.length:0};
 const group=useMemo(()=>currentRows.length?currentRows.reduce((a,r)=>a+avg(r),0)/currentRows.length:0,[currentRows]);
 async function save(){setMessage("Saving…");const res=await fetch("/api/customer-experience",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});if(res.status===428){location.href="/security/verify?next=/customer-experience";return;}const data=await res.json();if(!res.ok){setMessage(data.error||"Could not save");return;}setMessage("Saved.");router.refresh();}
 return <><div className="chain-kpi-rail"><div><span>GROUP RATING</span><strong>{group?group.toFixed(2):"—"}<i>/5</i></strong><em>{month.toString().padStart(2,"0")}/{year}</em></div><div><span>COMPLAINTS</span><strong>{currentRows.reduce((a,r)=>a+r.complaints_received,0)}</strong><em>CURRENT PERIOD</em></div><div className={currentRows.some(r=>r.complaints_unresolved>0)?"is-alert":""}><span>UNRESOLVED</span><strong>{currentRows.reduce((a,r)=>a+r.complaints_unresolved,0)}</strong><em>OWNER ATTENTION</em></div></div>
 <div className="chain-two-col"><section className="chain-card"><header><span>01</span><div><small>MONTHLY CUSTOMER PULSE</small><h2>Outlet experience register</h2></div></header><div className="chain-table-scroll"><div className="chain-table"><div className="chain-table-head"><span>OUTLET</span><span>GOOGLE</span><span>SWIGGY</span><span>ZOMATO</span><span>AVG</span><span>COMPLAINTS</span><span>OPEN</span></div>{currentRows.length?currentRows.map(r=><div className="chain-table-row" key={r.id}><strong>{r.outlet_name}<small>{r.outlet_code} · {String(r.month).padStart(2,"0")}/{r.year}</small></strong><span>{r.google_rating??"—"}</span><span>{r.swiggy_rating??"—"}</span><span>{r.zomato_rating??"—"}</span><b>{avg(r).toFixed(2)}</b><span>{r.complaints_received}</span><em className={r.complaints_unresolved?"bad-text":""}>{r.complaints_unresolved}</em></div>):<div className="chain-empty">No customer-experience records for this period yet.</div>}</div></div></section>
 <section className="chain-card chain-entry"><header><span>02</span><div><small>OWNER ENTRY</small><h2>Record monthly customer pulse</h2></div></header><div className="chain-form"><label><span>OUTLET</span><select value={form.outletId} onChange={e=>setForm({...form,outletId:e.target.value})}>{outlets.map(o=><option value={o.id} key={o.id}>{o.code} · {o.name}</option>)}</select></label><div className="chain-form-split"><label><span>YEAR</span><input type="number" value={form.year} onChange={e=>setForm({...form,year:Number(e.target.value)})}/></label><label><span>MONTH</span><input type="number" min="1" max="12" value={form.month} onChange={e=>setForm({...form,month:Number(e.target.value)})}/></label></div><div className="chain-form-split"><label><span>GOOGLE /5</span><input type="number" min="0" max="5" step="0.1" value={form.googleRating} onChange={e=>setForm({...form,googleRating:Number(e.target.value)})}/></label><label><span>SWIGGY /5</span><input type="number" min="0" max="5" step="0.1" value={form.swiggyRating} onChange={e=>setForm({...form,swiggyRating:Number(e.target.value)})}/></label></div><label><span>ZOMATO /5</span><input type="number" min="0" max="5" step="0.1" value={form.zomatoRating} onChange={e=>setForm({...form,zomatoRating:Number(e.target.value)})}/></label><div className="chain-form-split"><label><span>COMPLAINTS RECEIVED</span><input type="number" min="0" value={form.complaintsReceived} onChange={e=>setForm({...form,complaintsReceived:Number(e.target.value)})}/></label><label><span>UNRESOLVED</span><input type="number" min="0" value={form.complaintsUnresolved} onChange={e=>setForm({...form,complaintsUnresolved:Number(e.target.value)})}/></label></div><label><span>OWNER NOTES</span><textarea rows={4} value={form.ownerNotes} onChange={e=>setForm({...form,ownerNotes:e.target.value})}/></label><button className="command-button full" disabled={!form.outletId} onClick={()=>void save()}>SAVE CUSTOMER PULSE →</button>{message&&<p className="chain-message">{message}</p>}</div></section></div></>;
}
