"use client";
import { useState } from "react";
import type { ImportHistoryRow } from "@/lib/command-data";
import { PageLead, Panel, SectionHead, StatePill } from "@/components/ui";
const templates=[
 {type:"outlets",name:"Outlet master",file:"/templates/outlets.csv",fields:"outlet_code · name · city · targets · status"},
 {type:"daily_sales",name:"Daily sales",file:"/templates/daily-sales.csv",fields:"outlet_code · business_date · gross_sales · net_sales · orders"},
 {type:"channel_sales",name:"Channel sales",file:"/templates/channel-sales.csv",fields:"outlet_code · business_date · channel · net_sales · commission"},
 {type:"expenses",name:"Expenses",file:"/templates/expenses.csv",fields:"outlet_code · period · expense_date · category · amount"},
 {type:"staff",name:"Staff master",file:"/templates/staff.csv",fields:"employee_code · full_name · role_title · outlet_code · status"},
 {type:"monthly_financials",name:"Monthly financials",file:"/templates/monthly-financials.csv",fields:"outlet_code · period · net_revenue · costs · net_profit"},
 {type:"inventory",name:"Inventory snapshots",file:"/templates/inventory.csv",fields:"outlet_code · snapshot_date · item_sku · on_hand_qty · unit_cost"},
 {type:"vendors",name:"Vendors",file:"/templates/vendors.csv",fields:"vendor_code · name · contact · payment_terms"},
 {type:"purchases",name:"Purchases",file:"/templates/purchases.csv",fields:"outlet_code · purchase_date · vendor_code · invoice_no · total"},
 {type:"menu_performance",name:"Menu performance",file:"/templates/menu-performance.csv",fields:"outlet_code · period · item_sku · quantity_sold · net_sales"},
 {type:"cash_reconciliation",name:"Cash reconciliation",file:"/templates/cash-reconciliation.csv",fields:"outlet_code · business_date · expected_cash · banked_cash · variance"}
] as const;
type ImportType=typeof templates[number]["type"];
export function ImportCenter({importHistory}:{importHistory:ImportHistoryRow[]}){
 const[type,setType]=useState<ImportType>("daily_sales");const[file,setFile]=useState<File|null>(null);const[status,setStatus]=useState<"idle"|"validating"|"ready"|"committing"|"done"|"error">("idle");const[result,setResult]=useState<any>(null);const[error,setError]=useState("");
 const validate=async()=>{if(!file)return;setStatus("validating");setError("");try{const csv=await file.text();const r=await fetch("/api/imports/validate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,csv})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.issues?.[0]?`Row ${d.issues[0].row}: ${d.issues[0].message}`:d.error||"Validation failed");setResult({...d,csv});setStatus("ready");}catch(e){setStatus("error");setError(e instanceof Error?e.message:"Validation failed");}};
 const commit=async()=>{if(!file||!result?.csv)return;setStatus("committing");setError("");try{const r=await fetch("/api/imports/commit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,filename:file.name,csv:result.csv})});const d=await r.json();if(r.status===428){location.href=`/security/verify?next=${encodeURIComponent("/imports")}`;return;}if(!r.ok)throw new Error(d.error||"Import failed");setResult(d);setStatus("done");}catch(e){setStatus("error");setError(e instanceof Error?e.message:"Import failed");}};
 return <><PageLead code="18" eyebrow="DATA INTAKE / VALIDATION / IMPORTS" title="Bring real operating data in under control." copy="CSV files are validated against outlet codes, channel codes and business rules before any row can enter the command-center database."/>
 <div className="imports-grid command-gap"><Panel className="upload-panel"><SectionHead no="01" kicker="IMPORT STATION" title="Stage → validate → commit"/><div className="import-type-switch">{templates.map(t=><button key={t.type} className={type===t.type?"is-on":""} onClick={()=>{setType(t.type);setFile(null);setStatus("idle");setResult(null);}}>{t.name.toUpperCase()}</button>)}</div><label className="drop-zone"><input type="file" accept=".csv,text/csv" onChange={e=>{setFile(e.target.files?.[0]||null);setStatus("idle");setResult(null);setError("");}}/><span>SELECT CONTROLLED CSV</span><strong>{file?.name||"No file selected"}</strong><small>The file remains staged until validation succeeds and you explicitly commit it.</small><b>BROWSE FILE →</b></label>{file&&status==="idle"&&<button className="command-button full" onClick={()=>void validate()}>VALIDATE {type.replaceAll("_"," ").toUpperCase()} <span>→</span></button>}{status==="validating"&&<div className="import-state"><i/><span><strong>VALIDATING STRUCTURE</strong><small>Checking row formats and reference codes…</small></span></div>}{status==="ready"&&<div className="import-state is-ready"><i/><span><strong>{result.acceptedRows.toLocaleString("en-IN")} ROWS READY</strong><small>No validation exceptions detected.</small></span><button onClick={()=>void commit()}>COMMIT IMPORT →</button></div>}{status==="committing"&&<div className="import-state"><i/><span><strong>COMMITTING</strong><small>Fresh-MFA protected write in progress…</small></span></div>}{status==="done"&&<div className="import-state is-ready"><i/><span><strong>IMPORT COMPLETE</strong><small>{result.imported} rows written · Job {result.jobId}</small></span></div>}{error&&<div className="import-error"><b>IMPORT HELD</b><span>{error}</span></div>}</Panel>
 <Panel className="template-panel"><SectionHead no="02" kicker="CONTROLLED TEMPLATES" title="Start with exact columns"/><div className="template-list">{templates.map(t=><a href={t.file} download key={t.name}><span><strong>{t.name}</strong><small>{t.fields}</small></span><b>CSV ↓</b></a>)}</div></Panel>
 <Panel className="import-history"><SectionHead no="03" kicker="IMPORT HISTORY" title="Every load is attributable"/><div className="import-table"><div className="import-head"><span>FILE / TYPE</span><span>ROWS</span><span>ACCEPTED</span><span>REJECTED</span><span>STATUS</span><span>TIME</span></div>{importHistory.map(i=><div className="import-row" key={i.file}><span><strong>{i.file}</strong><small>{i.type}</small></span><b>{i.rows}</b><b>{i.accepted}</b><b className={i.rejected?"bad-text":""}>{i.rejected}</b><span><StatePill state={i.rejected?"watch":"steady"}>{i.status.toUpperCase()}</StatePill></span><span>{i.at}</span></div>)}</div><p className="demo-note">Every committed production import is attributable and recorded in <code>data_import_jobs</code>.</p></Panel>
 </div></>;
}
