"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
type Outlet={id:string;code:string;name:string};
type Asset={id:string;outlet_id:string;outlet_code:string;outlet_name:string;asset_code:string;name:string;category:string;status:string;installed_on?:string|null;last_service_on?:string|null;next_service_due?:string|null;vendor_name?:string|null;notes?:string|null};
type Incident={id:string;outlet_id:string;outlet_code:string;outlet_name:string;asset_id?:string|null;asset_code?:string|null;asset_name?:string|null;priority:string;issue:string;vendor_name?:string|null;estimated_cost?:number|null;actual_cost?:number|null;status:string;reported_at:string;resolution_notes?:string|null};
const emptyIncident=(outletId:string)=>({id:undefined as string|undefined,outletId,assetId:null as string|null,priority:'normal',issue:'',vendorName:'',estimatedCost:null as number|null,actualCost:null as number|null,status:'open',resolutionNotes:''});
const emptyAsset=(outletId:string)=>({id:undefined as string|undefined,outletId,assetCode:'',name:'',category:'Kitchen equipment',status:'operational',installedOn:null as string|null,lastServiceOn:null as string|null,nextServiceDue:null as string|null,vendorName:'',notes:''});
function dateValue(v?:string|null){return v?String(v).slice(0,10):'';}
export function MaintenanceControl({outlets,assets,incidents}:{outlets:Outlet[];assets:Asset[];incidents:Incident[]}){
 const router=useRouter();const first=outlets[0]?.id||'';const [mode,setMode]=useState<'incident'|'asset'>('incident');const [msg,setMsg]=useState('');const [incident,setIncident]=useState<any>(emptyIncident(first));const [asset,setAsset]=useState<any>(emptyAsset(first));
 async function post(url:string,body:any){setMsg('Saving…');const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(r.status===428){location.href='/security/verify?next=/maintenance';return;}const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.error||'Could not save');return;}setMsg('Saved.');router.refresh();}
 function editIncident(i:Incident){setMode('incident');setMsg('Editing existing incident.');setIncident({id:i.id,outletId:i.outlet_id,assetId:i.asset_id||null,priority:i.priority,issue:i.issue,vendorName:i.vendor_name||'',estimatedCost:i.estimated_cost==null?null:Number(i.estimated_cost),actualCost:i.actual_cost==null?null:Number(i.actual_cost),status:i.status,resolutionNotes:i.resolution_notes||''});document.getElementById('maintenance-entry')?.scrollIntoView({behavior:'smooth',block:'start'});}
 function editAsset(a:Asset){setMode('asset');setMsg('Editing existing equipment record.');setAsset({id:a.id,outletId:a.outlet_id,assetCode:a.asset_code,name:a.name,category:a.category,status:a.status,installedOn:dateValue(a.installed_on)||null,lastServiceOn:dateValue(a.last_service_on)||null,nextServiceDue:dateValue(a.next_service_due)||null,vendorName:a.vendor_name||'',notes:a.notes||''});document.getElementById('maintenance-entry')?.scrollIntoView({behavior:'smooth',block:'start'});}
 const open=incidents.filter(i=>i.status==='open'||i.status==='in_progress');
 return <><div className="chain-kpi-rail"><div><span>REGISTERED ASSETS</span><strong>{assets.length}</strong><em>CONTROLLED EQUIPMENT</em></div><div className={assets.some(a=>a.status==='down')?'is-alert':''}><span>EQUIPMENT DOWN</span><strong>{assets.filter(a=>a.status==='down').length}</strong><em>IMMEDIATE ACTION</em></div><div className={open.some(i=>i.priority==='critical')?'is-alert':''}><span>OPEN INCIDENTS</span><strong>{open.length}</strong><em>{open.filter(i=>i.priority==='critical').length} CRITICAL</em></div></div>
 <div className="maintenance-grid"><section className="chain-card maintenance-board"><header><span>01</span><div><small>MAINTENANCE CONTROL</small><h2>Equipment incidents</h2></div></header><div className="maintenance-list">{incidents.length?incidents.map(i=><button type="button" className={`maintenance-row is-${i.priority}`} key={i.id} onClick={()=>editIncident(i)}><b>{i.outlet_code}</b><span><strong>{i.asset_name||'General outlet issue'}</strong><small>{i.issue}</small></span><em>{i.priority.toUpperCase()}</em><span><strong>{i.status.replace('_',' ').toUpperCase()}</strong><small>{new Date(i.reported_at).toLocaleDateString('en-IN')} · EDIT</small></span></button>):<div className="chain-empty">No maintenance incidents recorded yet.</div>}</div></section>
 <section className="chain-card asset-board"><header><span>02</span><div><small>ASSET REGISTER</small><h2>Critical equipment</h2></div></header><div className="asset-list">{assets.length?assets.map(a=><button type="button" className="asset-row" key={a.id} onClick={()=>editAsset(a)}><b>{a.asset_code}</b><span><strong>{a.name}</strong><small>{a.outlet_code} · {a.category}</small></span><em className={a.status==='down'?'bad-text':''}>{a.status.toUpperCase()}</em><small>{a.next_service_due?`SERVICE ${new Date(a.next_service_due).toLocaleDateString('en-IN')} · EDIT`:'NO SERVICE DATE · EDIT'}</small></button>):<div className="chain-empty">No equipment registered yet.</div>}</div></section>
 <section className="chain-card chain-entry maintenance-entry" id="maintenance-entry"><header><span>03</span><div><small>OWNER CONTROL ENTRY</small><h2>{mode==='incident'?(incident.id?'Update equipment issue':'Log equipment issue'):(asset.assetCode?'Register / update equipment':'Register equipment')}</h2></div><div className="segmented"><button className={mode==='incident'?'is-on':''} onClick={()=>{setMode('incident');setIncident(emptyIncident(first));setMsg('')}}>INCIDENT</button><button className={mode==='asset'?'is-on':''} onClick={()=>{setMode('asset');setAsset(emptyAsset(first));setMsg('')}}>ASSET</button></div></header>
 {mode==='incident'?<div className="chain-form"><label><span>OUTLET</span><select value={incident.outletId} onChange={e=>setIncident({...incident,outletId:e.target.value,assetId:null})}>{outlets.map(o=><option value={o.id} key={o.id}>{o.code} · {o.name}</option>)}</select></label><label><span>ASSET</span><select value={incident.assetId||''} onChange={e=>setIncident({...incident,assetId:e.target.value||null})}><option value="">GENERAL / NO ASSET</option>{assets.filter(a=>a.outlet_id===incident.outletId).map(a=><option value={a.id} key={a.id}>{a.asset_code} · {a.name}</option>)}</select></label><div className="chain-form-split"><label><span>PRIORITY</span><select value={incident.priority} onChange={e=>setIncident({...incident,priority:e.target.value})}><option>low</option><option>normal</option><option>high</option><option>critical</option></select></label><label><span>STATUS</span><select value={incident.status} onChange={e=>setIncident({...incident,status:e.target.value})}><option>open</option><option>in_progress</option><option>resolved</option><option>cancelled</option></select></label></div><label><span>ISSUE</span><textarea rows={4} value={incident.issue} onChange={e=>setIncident({...incident,issue:e.target.value})}/></label><div className="chain-form-split"><label><span>ESTIMATED COST</span><input type="number" min="0" value={incident.estimatedCost??''} onChange={e=>setIncident({...incident,estimatedCost:e.target.value?Number(e.target.value):null})}/></label><label><span>ACTUAL COST</span><input type="number" min="0" value={incident.actualCost??''} onChange={e=>setIncident({...incident,actualCost:e.target.value?Number(e.target.value):null})}/></label></div><label><span>VENDOR</span><input value={incident.vendorName} onChange={e=>setIncident({...incident,vendorName:e.target.value})}/></label><label><span>RESOLUTION NOTES</span><textarea rows={3} value={incident.resolutionNotes} onChange={e=>setIncident({...incident,resolutionNotes:e.target.value})}/></label>{incident.id&&<div className="maintenance-status-actions"><button type="button" onClick={()=>void post('/api/maintenance/incidents',{...incident,status:'open'})}>REOPEN</button><button type="button" onClick={()=>void post('/api/maintenance/incidents',{...incident,status:'in_progress'})}>MARK IN PROGRESS</button><button type="button" onClick={()=>void post('/api/maintenance/incidents',{...incident,status:'resolved'})}>MARK RESOLVED</button></div>}<button className="command-button full" disabled={!incident.outletId||incident.issue.trim().length<3} onClick={()=>void post('/api/maintenance/incidents',incident)}>{incident.id?'UPDATE INCIDENT →':'SAVE MAINTENANCE INCIDENT →'}</button>{msg&&<p className="chain-message">{msg}</p>}</div>
 :<div className="chain-form"><label><span>OUTLET</span><select value={asset.outletId} onChange={e=>setAsset({...asset,outletId:e.target.value})}>{outlets.map(o=><option value={o.id} key={o.id}>{o.code} · {o.name}</option>)}</select></label><div className="chain-form-split"><label><span>ASSET CODE</span><input value={asset.assetCode} onChange={e=>setAsset({...asset,assetCode:e.target.value.toUpperCase()})}/></label><label><span>STATUS</span><select value={asset.status} onChange={e=>setAsset({...asset,status:e.target.value})}><option>operational</option><option>attention</option><option>down</option><option>retired</option></select></label></div><label><span>EQUIPMENT NAME</span><input value={asset.name} onChange={e=>setAsset({...asset,name:e.target.value})}/></label><label><span>CATEGORY</span><input value={asset.category} onChange={e=>setAsset({...asset,category:e.target.value})}/></label><div className="chain-form-split"><label><span>INSTALLED ON</span><input type="date" value={asset.installedOn||''} onChange={e=>setAsset({...asset,installedOn:e.target.value||null})}/></label><label><span>LAST SERVICE</span><input type="date" value={asset.lastServiceOn||''} onChange={e=>setAsset({...asset,lastServiceOn:e.target.value||null})}/></label></div><label><span>NEXT SERVICE DUE</span><input type="date" value={asset.nextServiceDue||''} onChange={e=>setAsset({...asset,nextServiceDue:e.target.value||null})}/></label><label><span>VENDOR</span><input value={asset.vendorName} onChange={e=>setAsset({...asset,vendorName:e.target.value})}/></label><label><span>NOTES</span><textarea rows={3} value={asset.notes} onChange={e=>setAsset({...asset,notes:e.target.value})}/></label><button className="command-button full" disabled={!asset.outletId||!asset.assetCode||asset.name.trim().length<2} onClick={()=>void post('/api/maintenance/assets',asset)}>{asset.id?'UPDATE EQUIPMENT →':'SAVE EQUIPMENT →'}</button>{msg&&<p className="chain-message">{msg}</p>}</div>}</section></div></>;
}
