"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function MfaSetupForm({secret,email}:{secret:string;email:string}){
  const router=useRouter();const[code,setCode]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[recovery,setRecovery]=useState<string[]|null>(null);
  if(recovery)return <section className="auth-control-card recovery-card"><span className="auth-kicker">RECOVERY SET / ONE-TIME CODES</span><h2>Store these away from this device.</h2><p>Each code works once. The Command Center stores only cryptographic hashes, so this list cannot be shown again.</p><div className="recovery-grid">{recovery.map(x=><code key={x}>{x}</code>)}</div><button className="command-button full" onClick={()=>router.replace("/overview")}>I SAVED THE CODES <span>→</span></button></section>;
  return <section className="auth-control-card"><span className="auth-kicker">GM AUTHENTICATOR / TOTP</span><h2>Bind a second factor.</h2><p>Use Google Authenticator, Microsoft Authenticator, 1Password or another standards-based TOTP app.</p><div className="setup-instructions"><span>01</span><p>Choose <b>Enter setup key</b> or <b>Manual entry</b>.</p><span>02</span><p>Account name: <b>{email}</b></p><span>03</span><p>Key type: <b>Time based</b></p></div><div className="setup-secret"><small>SETUP KEY</small><code>{secret}</code><em>Keep this secret. Anyone with it can generate valid codes.</em></div><label className="secure-field"><span>6-DIGIT AUTHENTICATOR CODE</span><input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="000000"/></label><button className="command-button full" disabled={busy||code.length!==6} onClick={async()=>{setBusy(true);setError("");try{const r=await fetch("/api/security/mfa/enroll",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not enable MFA");setRecovery(d.recoveryCodes||[]);}catch(e){setError(e instanceof Error?e.message:"Could not enable MFA");}finally{setBusy(false);}}}>{busy?"VERIFYING…":"ENABLE GM AUTHENTICATOR"} <span>→</span></button>{error&&<small className="auth-error">{error}</small>}</section>;
}
