"use client";
import Link from "next/link";
import { useState } from "react";
import type { Outlet } from "@/lib/demo-data";
import { compactMoney } from "@/lib/demo-data";
import { Delta, Meter, PageLead, Panel, SectionHead, StatePill } from "@/components/ui";
import { OutletCreateButton } from "@/components/qa-record-actions";
export function OutletsControl({outlets,label}:{outlets:Outlet[];label:string}){
 const [selected,setSelected]=useState(outlets[0]);const score=(o:Outlet)=>Math.max(0,Math.min(100,Math.round(62+o.margin/1.6+o.delta/3-(o.foodCost>36?8:0))));
 if(!selected)return <><PageLead code="02" eyebrow="OUTLET CONTROL / NETWORK VIEW" title="Every location. Same operating language." copy="The backend is ready. Add or import the outlet master to activate the network view." action={<OutletCreateButton/>}/><Panel><SectionHead no="01" kicker="WAITING FOR OUTLETS" title="No production outlet records yet"/><p>Load your outlet codes and names before importing sales, staff, expenses or inventory.</p></Panel></>;
 return <><PageLead code="02" eyebrow={`OUTLET CONTROL / NETWORK VIEW / ${label}`} title="Every location. Same operating language." copy="Compare outlet economics, targets, staffing and operating pressure without losing the context behind each store." action={<OutletCreateButton/>} meta={<><span>{outlets.length} ACTIVE LOCATIONS</span><span>{outlets.filter(o=>o.state==='critical').length} CRITICAL</span><span>{outlets.filter(o=>o.state==='watch').length} WATCH</span></>}/>
 <div className="summary-ribbon"><span><small>ACTIVE OUTLETS</small><strong>{String(outlets.length).padStart(2,"0")}</strong></span><span><small>AHEAD</small><strong>{String(outlets.filter(o=>o.state==='ahead').length).padStart(2,"0")}</strong></span><span><small>WATCH</small><strong>{String(outlets.filter(o=>o.state==='watch').length).padStart(2,"0")}</strong></span><span><small>CRITICAL</small><strong>{String(outlets.filter(o=>o.state==='critical').length).padStart(2,"0")}</strong></span><span><small>GROUP STAFF</small><strong>{outlets.reduce((s,o)=>s+o.staff,0)}</strong></span><span><small>AVG SCORE</small><strong>{outlets.length?Math.round(outlets.reduce((s,o)=>s+score(o),0)/outlets.length):0}</strong></span></div>
 <div className="two-column outlet-network-grid command-gap"><Panel className="outlet-network"><SectionHead no="01" kicker="NETWORK MATRIX" title="Outlet control board"/><div className="outlet-cards">{outlets.map((o,i)=><button key={o.id} onClick={()=>setSelected(o)} className={selected.id===o.id?"outlet-control-card is-selected":"outlet-control-card"}><div className="outlet-card-top"><span>{String(i+1).padStart(2,"0")} / {o.id}</span><StatePill state={o.state}>{o.state.toUpperCase()}</StatePill></div><h3>{o.name}</h3><p>{o.city} · {o.manager}</p><div className="outlet-card-score"><strong>{score(o)}</strong><span>GM SCORE</span><i style={{"--score":`${score(o)}%`} as React.CSSProperties}/></div><div className="outlet-card-fin"><span><small>REVENUE</small><strong>{compactMoney(o.revenue)}</strong></span><span><small>PROFIT</small><strong>{compactMoney(o.profit)}</strong></span></div><div className="outlet-card-bottom"><Delta value={o.delta}/><small>VS PRIOR PERIOD · {o.staff} STAFF</small></div></button>)}</div></Panel>
 <Panel className="detail-console" label="OUTLET COMMAND VIEW"><div className="detail-kicker">{selected.id} / {label}</div><div className="detail-title-line"><h2>{selected.name}</h2><StatePill state={selected.state}>{selected.state.toUpperCase()}</StatePill></div><p>Current month position against store and group controls.</p><div className="console-score"><strong>{score(selected)}</strong><span>OPERATING SCORE</span></div><div className="console-grid"><div><small>REVENUE</small><strong>{compactMoney(selected.revenue)}</strong></div><div><small>PROFIT</small><strong>{compactMoney(selected.profit)}</strong></div><div><small>MARGIN</small><strong>{selected.margin}%</strong></div><div><small>AOV</small><strong>₹{selected.aov}</strong></div><div><small>ORDERS</small><strong>{selected.orders.toLocaleString("en-IN")}</strong></div><div><small>STAFF</small><strong>{selected.staff}</strong></div><div><small>RATING</small><strong>{selected.rating||"—"}</strong></div><div><small>CASH VAR.</small><strong className={Math.abs(selected.cashVariance)>2000?"bad-text":""}>{compactMoney(selected.cashVariance)}</strong></div></div><div className="console-controls"><label><span>MONTH TARGET</span><Meter value={selected.target}/></label><label><span>FOOD COST</span><Meter value={Math.max(0,100-(selected.foodCost-28)*4)} tone={selected.foodCost>35?"red":"teal"}/></label><label><span>LABOUR CONTROL</span><Meter value={Math.max(0,100-(selected.labourCost-12)*5)} tone={selected.labourCost>18?"red":"teal"}/></label><label><span>INVENTORY HEALTH</span><Meter value={selected.inventoryHealth} tone={selected.inventoryHealth<75?"red":"teal"}/></label></div><Link href={`/outlets/${selected.id}`} className="command-button full">OPEN {selected.id} COMMAND VIEW <span>→</span></Link></Panel></div></>;
}
