"use client";

import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import type { ReactNode } from "react";

type OutletOption={id:string;code:string;name:string};
type OwnerOption={displayName:string;email:string};
type ExpenseCategory={code:string;name:string};

function Modal({title,kicker,onClose,children}:{title:string;kicker:string;onClose:()=>void;children:ReactNode}){
  const cardRef=useRef<HTMLElement>(null);const returnFocusRef=useRef<HTMLElement|null>(null);const closeRef=useRef(onClose);closeRef.current=onClose;
  useEffect(()=>{const node=cardRef.current;returnFocusRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null;if(!node)return;const items=()=>Array.from(node.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])'));const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();closeRef.current();return;}if(event.key!=="Tab")return;const all=items();if(!all.length)return;const first=all[0],last=all[all.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};window.addEventListener("keydown",key);queueMicrotask(()=>items()[0]?.focus());return()=>{window.removeEventListener("keydown",key);returnFocusRef.current?.focus();};},[]);
  return <div className="record-modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={onClose}>
    <section ref={cardRef} className="record-modal__card" onMouseDown={e=>e.stopPropagation()}>
      <header><div><small>{kicker}</small><h2>{title}</h2></div><button type="button" onClick={onClose} aria-label="Close form">×</button></header>
      {children}
    </section>
  </div>;
}

async function jsonRequest(url:string,init:RequestInit,nextPath:string){
  const r=await fetch(url,init);
  if(r.status===428){location.href=`/security/verify?next=${encodeURIComponent(nextPath)}`;return null;}
  const d=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(d.error||"Request failed");
  return d;
}

export function OutletCreateButton(){
  const router=useRouter();const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
  const[form,setForm]=useState({code:"",name:"",legalName:"",city:"Bengaluru",address:"",openingDate:null as string|null,status:"active",monthlyRevenueTarget:null as number|null,monthlyProfitTarget:null as number|null,foodCostTargetPct:null as number|null,labourCostTargetPct:null as number|null});
  async function save(){setBusy(true);setMsg("");try{const d=await jsonRequest("/api/outlets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)},"/outlets");if(d){setMsg("Outlet created.");router.refresh();setTimeout(()=>setOpen(false),350);}}catch(e){setMsg(e instanceof Error?e.message:"Could not create outlet");}finally{setBusy(false)}}
  return <><button className="command-button" onClick={()=>setOpen(true)}>ADD OUTLET RECORD <span>→</span></button>{open&&<Modal title="Add outlet record" kicker="OWNER CONTROL / OUTLET MASTER" onClose={()=>setOpen(false)}><div className="record-form"><div className="record-form__split"><label><span>OUTLET CODE</span><input value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} placeholder="KOR"/></label><label><span>STATUS</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">ACTIVE</option><option value="planned">PLANNED</option><option value="temporarily_closed">TEMPORARILY CLOSED</option><option value="closed">CLOSED</option></select></label></div><label><span>OUTLET NAME</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>LEGAL NAME (OPTIONAL)</span><input value={form.legalName} onChange={e=>setForm({...form,legalName:e.target.value})}/></label><div className="record-form__split"><label><span>CITY</span><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label><span>OPENING DATE</span><input type="date" value={form.openingDate||""} onChange={e=>setForm({...form,openingDate:e.target.value||null})}/></label></div><label><span>ADDRESS</span><textarea rows={3} value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><div className="record-form__split"><label><span>MONTHLY REVENUE TARGET</span><input type="number" min="0" value={form.monthlyRevenueTarget??""} onChange={e=>setForm({...form,monthlyRevenueTarget:e.target.value?Number(e.target.value):null})}/></label><label><span>MONTHLY PROFIT TARGET</span><input type="number" value={form.monthlyProfitTarget??""} onChange={e=>setForm({...form,monthlyProfitTarget:e.target.value?Number(e.target.value):null})}/></label></div><div className="record-form__split"><label><span>FOOD COST TARGET %</span><input type="number" min="0" max="100" step="0.1" value={form.foodCostTargetPct??""} onChange={e=>setForm({...form,foodCostTargetPct:e.target.value?Number(e.target.value):null})}/></label><label><span>LABOUR COST TARGET %</span><input type="number" min="0" max="100" step="0.1" value={form.labourCostTargetPct??""} onChange={e=>setForm({...form,labourCostTargetPct:e.target.value?Number(e.target.value):null})}/></label></div><button className="command-button full" disabled={busy||!form.code||!form.name} onClick={()=>void save()}>{busy?"SAVING…":"CREATE OUTLET →"}</button>{msg&&<p className="record-message">{msg}</p>}</div></Modal>}</>;
}

export function TaskCreateButton({outlets,owners,autoOpen=false}:{outlets:OutletOption[];owners:OwnerOption[];autoOpen?:boolean}){
  const router=useRouter();const[open,setOpen]=useState(autoOpen);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
  const[form,setForm]=useState({outletId:"",title:"",description:"",priority:"normal",assignedOwnerEmail:"",dueLocal:""});
  async function save(){setBusy(true);setMsg("");try{const dueAt=form.dueLocal?new Date(form.dueLocal).toISOString():null;const d=await jsonRequest("/api/tasks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({outletId:form.outletId||null,alertId:null,title:form.title,description:form.description,priority:form.priority,status:"open",assignedOwnerEmail:form.assignedOwnerEmail||null,dueAt})},"/tasks");if(d){setMsg("Task created.");router.refresh();setTimeout(()=>setOpen(false),350);}}catch(e){setMsg(e instanceof Error?e.message:"Could not create task");}finally{setBusy(false)}}
  return <><button className="command-button" onClick={()=>setOpen(true)}>CREATE TASK <span>→</span></button>{open&&<Modal title="Create owner task" kicker="OWNER ACTION / ACCOUNTABILITY" onClose={()=>setOpen(false)}><div className="record-form"><label><span>TASK</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label><span>DESCRIPTION</span><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="record-form__split"><label><span>OUTLET</span><select value={form.outletId} onChange={e=>setForm({...form,outletId:e.target.value})}><option value="">GROUP / HQ</option>{outlets.map(o=><option key={o.id} value={o.id}>{o.code} · {o.name}</option>)}</select></label><label><span>PRIORITY</span><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">LOW</option><option value="normal">NORMAL</option><option value="high">HIGH</option><option value="urgent">URGENT</option></select></label></div><div className="record-form__split"><label><span>ASSIGNED OWNER</span><select value={form.assignedOwnerEmail} onChange={e=>setForm({...form,assignedOwnerEmail:e.target.value})}><option value="">UNASSIGNED</option>{owners.map(o=><option key={o.email} value={o.email}>{o.displayName}</option>)}</select></label><label><span>DUE DATE / TIME</span><input type="datetime-local" value={form.dueLocal} onChange={e=>setForm({...form,dueLocal:e.target.value})}/></label></div><button className="command-button full" disabled={busy||form.title.trim().length<3} onClick={()=>void save()}>{busy?"SAVING…":"CREATE TASK →"}</button>{msg&&<p className="record-message">{msg}</p>}</div></Modal>}</>;
}

export function DocumentCreateButton({outlets}:{outlets:OutletOption[]}){
  const router=useRouter();const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
  const[form,setForm]=useState({outletId:"",documentType:"License",title:"",storageKey:"",expiresOn:null as string|null,confidential:true});
  async function save(){setBusy(true);setMsg("");try{const d=await jsonRequest("/api/documents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,outletId:form.outletId||null})},"/documents");if(d){setMsg("Document record added.");router.refresh();setTimeout(()=>setOpen(false),350);}}catch(e){setMsg(e instanceof Error?e.message:"Could not add document");}finally{setBusy(false)}}
  return <><button className="command-button" onClick={()=>setOpen(true)}>ADD DOCUMENT RECORD <span>→</span></button>{open&&<Modal title="Add document record" kicker="OWNER CONTROL / DOCUMENT VAULT" onClose={()=>setOpen(false)}><div className="record-form"><div className="record-form__split"><label><span>SCOPE</span><select value={form.outletId} onChange={e=>setForm({...form,outletId:e.target.value})}><option value="">GROUP / HQ</option>{outlets.map(o=><option key={o.id} value={o.id}>{o.code} · {o.name}</option>)}</select></label><label><span>DOCUMENT TYPE</span><input value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})}/></label></div><label><span>TITLE</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label><span>SECURE FILE / REFERENCE KEY</span><input value={form.storageKey} onChange={e=>setForm({...form,storageKey:e.target.value})} placeholder="Private storage key, Drive reference, or controlled URL"/></label><div className="record-form__split"><label><span>EXPIRY DATE</span><input type="date" value={form.expiresOn||""} onChange={e=>setForm({...form,expiresOn:e.target.value||null})}/></label><label className="record-checkbox"><span>CONFIDENTIAL</span><input type="checkbox" checked={form.confidential} onChange={e=>setForm({...form,confidential:e.target.checked})}/></label></div><button className="command-button full" disabled={busy||!form.title||!form.storageKey} onClick={()=>void save()}>{busy?"SAVING…":"ADD DOCUMENT →"}</button>{msg&&<p className="record-message">{msg}</p>}</div></Modal>}</>;
}

export function ExpenseEntryControl({outlets,categories,year,month}:{outlets:OutletOption[];categories:ExpenseCategory[];year:number;month:number}){
  const router=useRouter();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");const now=new Date();const today=now.toISOString().slice(0,10);const periodPrefix=`${year}-${String(month).padStart(2,"0")}`;const defaultExpenseDate=today.startsWith(`${periodPrefix}-`)?today:`${periodPrefix}-01`;
  const[form,setForm]=useState({outletId:outlets[0]?.id||"",year,month,expenseDate:defaultExpenseDate,categoryCode:categories[0]?.code||"",vendorName:"",referenceNo:"",amount:0,description:""});
  async function save(){setBusy(true);setMsg("");try{const d=await jsonRequest("/api/expenses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)},"/expenses");if(d){setMsg("Expense posted.");router.refresh();setForm({...form,amount:0,referenceNo:"",description:""});}}catch(e){setMsg(e instanceof Error?e.message:"Could not post expense");}finally{setBusy(false)}}
  return <section className="panel expense-entry-panel" id="expense-entry"><div className="section-head"><div className="section-head__left"><span className="section-no">05</span><div><small>OWNER ENTRY</small><h2>Post an expense</h2></div></div></div><div className="record-form record-form--inline"><div className="record-form__split"><label><span>OUTLET</span><select value={form.outletId} onChange={e=>setForm({...form,outletId:e.target.value})}>{outlets.map(o=><option key={o.id} value={o.id}>{o.code} · {o.name}</option>)}</select></label><label><span>CATEGORY</span><select value={form.categoryCode} onChange={e=>setForm({...form,categoryCode:e.target.value})}>{categories.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label></div><div className="record-form__split"><label><span>EXPENSE DATE</span><input type="date" value={form.expenseDate} onChange={e=>setForm({...form,expenseDate:e.target.value})}/></label><label><span>AMOUNT</span><input type="number" min="0" step="0.01" value={form.amount||""} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></label></div><div className="record-form__split"><label><span>VENDOR</span><input value={form.vendorName} onChange={e=>setForm({...form,vendorName:e.target.value})}/></label><label><span>REFERENCE</span><input value={form.referenceNo} onChange={e=>setForm({...form,referenceNo:e.target.value})}/></label></div><label><span>DESCRIPTION</span><textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="command-button full" disabled={busy||!form.outletId||!form.categoryCode||form.amount<=0} onClick={()=>void save()}>{busy?"POSTING…":"POST EXPENSE →"}</button>{msg&&<p className="record-message">{msg}</p>}</div></section>;
}

export function TaskDoneButton({id}:{id:string}){
  const router=useRouter();const[busy,setBusy]=useState(false);
  return <button className="task-status-button" disabled={busy} onClick={async()=>{setBusy(true);try{const d=await jsonRequest(`/api/tasks/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:"done"})},"/tasks");if(d)router.refresh();}catch(e){alert(e instanceof Error?e.message:"Could not complete task");}finally{setBusy(false);}}}>{busy?"SAVING…":"MARK DONE"}</button>;
}
