import { compactMoney } from "@/lib/demo-data";
import { Delta, Meter, PageLead, Panel, SectionHead, StatePill } from "@/components/ui";
import { getInventoryRisks,getOutlets,getReportingContext } from "@/lib/command-data";
export default async function InventoryPage(){const ctx=await getReportingContext();const [inventoryRisks,outlets]=await Promise.all([getInventoryRisks(),getOutlets(ctx)]);const stockValue=inventoryRisks.reduce((s,r)=>s+r.stockValue,0),low=inventoryRisks.filter(r=>r.outlets>0);return <>
<PageLead code="07" eyebrow={`INVENTORY / STOCK / ${ctx.label}`} title="Stock risk before it becomes service risk." copy="Monitor latest stock snapshots, reorder pressure and wastage value across outlets." action={<a className="command-button" href="/imports">IMPORT STOCK COUNT <span>→</span></a>} meta={<><span>SNAPSHOT MODEL</span><span>OUTLET COUNTS</span><span>WASTAGE CONTROL</span></>}/>
<div className="inventory-kpis"><div><span>TRACKED STOCK VALUE</span><strong>{compactMoney(stockValue)}</strong><small>LATEST SNAPSHOTS</small></div><div><span>LOW STOCK ITEMS</span><strong>{low.length}</strong><small>REORDER FLOOR</small></div><div><span>OUTLETS</span><strong>{outlets.length}</strong><small>ACTIVE / TEMP CLOSED</small></div><div><span>COUNT DATA</span><strong>{inventoryRisks.length}</strong><small>ITEMS IN LATEST SET</small></div><div><span>WASTAGE SIGNAL</span><strong>{inventoryRisks.length?`${(inventoryRisks.reduce((s,r)=>s+r.variance,0)/inventoryRisks.length).toFixed(1)}%`:"0%"}</strong><small>VALUE RATIO</small></div></div>
<div className="inventory-grid command-gap"><Panel className="inventory-risk"><SectionHead no="01" kicker="STOCK RISK" title="Items below control floor"/><div className="risk-table"><div className="risk-head"><span>ITEM / SKU</span><span>CATEGORY</span><span>OUTLETS</span><span>COVER EST.</span><span>WASTAGE</span><span>STOCK VALUE</span><span>ACTION</span></div>{inventoryRisks.map(r=><div className="risk-row" key={r.sku}><span><b>{r.item}</b><small>{r.sku}</small></span><span>{r.category}</span><span>{r.outlets}</span><span className={r.days<2?"bad-text":""}>{r.days.toFixed(1)} days*</span><span><Delta value={r.variance}/></span><strong>{compactMoney(r.stockValue)}</strong><span><StatePill state={r.outlets>0?"critical":r.days<3?"watch":"steady"}>{r.action.toUpperCase()}</StatePill></span></div>)}</div><p className="panel-note">*Cover estimate is derived from the imported reorder-point ratio until consumption data is integrated.</p></Panel>
<Panel className="count-discipline"><SectionHead no="02" kicker="OUTLET COVERAGE" title="Inventory command status"/><div className="count-coverage">{outlets.map((o)=><div key={o.id}><span><b>{o.id}</b><strong>{o.name}</strong><small>{o.inventoryHealth}% inventory health</small></span><Meter value={o.inventoryHealth} tone={o.inventoryHealth<75?"red":"teal"}/></div>)}</div></Panel>
<Panel className="wastage-panel"><SectionHead no="03" kicker="WASTAGE" title="Items with value leakage"/><div className="wastage-bars">{inventoryRisks.filter(r=>r.variance>0).slice(0,6).map(r=><div key={r.sku}><span>{r.item}</span><i><b style={{width:`${Math.min(100,r.variance*5)}%`}}/></i><strong>{r.variance.toFixed(1)}%</strong><em>{compactMoney(r.stockValue)}</em></div>)}</div></Panel>
<Panel className="inventory-transfer" tone="cream"><SectionHead no="04" kicker="CONTROL NOTE" title="Move stock before buying more"/><p className="panel-note">The backend preserves outlet-level stock snapshots. Inter-outlet transfer recommendations should only be generated once comparable stock counts are available for the same item across multiple outlets.</p></Panel></div></>}
