import { getPeopleDashboardData } from "@/lib/people";
import { getAlerts } from "@/lib/command-data";
import { PageLead, Panel, SectionHead, StatePill } from "@/components/ui";
import { AlertAcknowledgeButton, ControlRefreshButton } from "@/components/backend-action-controls";
export default async function AlertsPage(){const [people,baseAlerts]=await Promise.all([getPeopleDashboardData(),getAlerts()]);const existingExit=new Set(baseAlerts.map(a=>a.title));const exitAlerts=people.staff.filter(s=>s.status==="notice"&&s.daysRemaining!=null&&s.daysRemaining<=30).map((s,i)=>({id:`PEOPLE-${String(i+1).padStart(2,"0")}`,severity:s.daysRemaining!=null&&s.daysRemaining<=7?"critical":"watch",outlet:s.outletCode,title:`${s.fullName} is leaving in ${s.daysRemaining} days`,detail:`Last working day ${s.lastWorkingDate||"not set"} · ${s.roleTitle}`,age:"PEOPLE",owner:"Owner"})).filter(a=>!existingExit.has(a.title));const allAlerts=[...exitAlerts,...baseAlerts];const counts={critical:allAlerts.filter(a=>a.severity==='critical').length,high:allAlerts.filter(a=>a.severity==='high').length,watch:allAlerts.filter(a=>a.severity==='watch').length};return <>
<PageLead code="13" eyebrow="EXCEPTION CONTROL / ALERTS / RULES" title="Only show what needs attention." copy="Material deviations surface here with ownership, acknowledgement and resolution history." action={<ControlRefreshButton/>} meta={<><span>RULE-BASED</span><span>OWNER ACKNOWLEDGEMENT</span><span>AUDITED RESOLUTION</span></>}/>
<div className="alert-summary"><span><small>OPEN</small><strong>{allAlerts.length}</strong></span><span><small>CRITICAL</small><strong>{counts.critical}</strong></span><span><small>HIGH</small><strong>{counts.high}</strong></span><span><small>WATCH</small><strong>{counts.watch}</strong></span></div>
<div className="alerts-grid command-gap"><Panel className="alert-command"><SectionHead no="01" kicker="OPEN QUEUE" title="Current exceptions"/><div className="alert-command-list">{allAlerts.map((a,i)=><div key={a.id} className={`alert-command-row is-${a.severity}`}><span className="alert-number">{String(i+1).padStart(2,"0")}</span><div><small>{a.outlet} / {a.age}</small><strong>{a.title}</strong><p>{a.detail}</p></div><span><StatePill state={a.severity==="critical"?"critical":a.severity==="high"||a.severity==="watch"?"watch":"info"}>{a.severity.toUpperCase()}</StatePill><b>{a.owner}</b></span><AlertAcknowledgeButton id={a.id}/></div>)}</div></Panel>
<Panel className="rule-engine"><SectionHead no="02" kicker="RULE ENGINE" title="Automated control library"/><div className="rule-list"><div><b>FC-01</b><span><strong>Food cost control</strong><small>Actual above target + 3 pts</small></span><em>ACTIVE</em></div><div><b>REV-02</b><span><strong>Revenue trajectory</strong><small>Projected close below 90% target</small></span><em>ACTIVE</em></div><div><b>LAB-03</b><span><strong>Labour cost</strong><small>Above outlet target + 3 pts</small></span><em>ACTIVE</em></div><div><b>CASH-04</b><span><strong>Cash reconciliation</strong><small>Daily variance above ₹2,000</small></span><em>ACTIVE</em></div><div><b>DOC-05</b><span><strong>Document expiry</strong><small>Critical record inside 30 days</small></span><em>ACTIVE</em></div><div><b>HR-07</b><span><strong>Employee exit watch</strong><small>Notice employee inside final 30 days</small></span><em>ACTIVE</em></div><div><b>CX-08</b><span><strong>Customer experience</strong><small>Rating or complaint threshold</small></span><em>ACTIVE</em></div><div><b>MNT-09</b><span><strong>Maintenance critical</strong><small>High / critical incident opened</small></span><em>ACTIVE</em></div><div><b>AUD-10</b><span><strong>Outlet audit floor</strong><small>Monthly audit below 70 / 100</small></span><em>ACTIVE</em></div></div></Panel>
<Panel className="alert-response" tone="cream"><SectionHead no="03" kicker="RESPONSE MODEL" title="Owner-controlled resolution"/><div className="response-kpis"><div><span>OPEN ALERTS</span><strong>{allAlerts.length}</strong></div><div><span>CRITICAL / HIGH</span><strong>{counts.critical+counts.high}</strong></div></div></Panel></div></>}
