import { randomUUID } from "node:crypto";
import { z } from "zod";
import { requireApiProfile } from "@/lib/access-control";
import { recordSecurityEvent } from "@/lib/audit";
import { db } from "@/lib/db";
import { consumeRateLimit, enforceSameOrigin, internalApiError, rateLimitResponse, readJsonWithLimit, requestParseError } from "@/lib/http-security";
import { validateImport } from "@/lib/imports";
import { hasFreshFinancialMfa } from "@/lib/mfa";
import { refreshControlAlerts } from "@/lib/control-rules";
const schema=z.object({type:z.enum(["outlets","daily_sales","channel_sales","expenses","staff","monthly_financials","inventory","vendors","purchases","menu_performance","cash_reconciliation"]),filename:z.string().trim().min(1).max(180),csv:z.string().min(1).max(2_000_000)});
export async function POST(req:Request){const same=enforceSameOrigin(req);if(same)return same;const access=await requireApiProfile("/api/imports/commit");if("response" in access)return access.response;const profile=access.profile;if(!(await hasFreshFinancialMfa()))return Response.json({error:"Fresh MFA required",code:"MFA_FRESH_REQUIRED"},{status:428});const rate=await consumeRateLimit("dash-import-commit",8,600,"user");if(!rate.allowed)return rateLimitResponse(rate.retryAfter);
 try{const parsed=schema.safeParse(await readJsonWithLimit(req,2_100_000));if(!parsed.success)return Response.json({error:"Invalid import payload"},{status:400});const validated=await validateImport(parsed.data.type,parsed.data.csv);if(!validated.ok)return Response.json({error:"Import no longer validates",issues:validated.issues},{status:409});const payload=JSON.stringify(validated.rows);const count=validated.acceptedRows;const jobId=randomUUID();const sql=db();await sql.begin("isolation level serializable",async(tx)=>{
 if(parsed.data.type==="outlets"){await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(outlet_code text,name text,legal_name text,city text,address text,opening_date text,status text,monthly_revenue_target text,monthly_profit_target text,food_cost_target_pct text,labour_cost_target_pct text)) INSERT INTO outlets(code,name,legal_name,city,address,opening_date,status,monthly_revenue_target,monthly_profit_target,food_cost_target_pct,labour_cost_target_pct) SELECT x.outlet_code,x.name,NULLIF(x.legal_name,''),x.city,NULLIF(x.address,''),NULLIF(x.opening_date,'')::date,x.status,NULLIF(x.monthly_revenue_target,'')::numeric,NULLIF(x.monthly_profit_target,'')::numeric,NULLIF(x.food_cost_target_pct,'')::numeric,NULLIF(x.labour_cost_target_pct,'')::numeric FROM input x ON CONFLICT(code) DO UPDATE SET name=EXCLUDED.name,legal_name=EXCLUDED.legal_name,city=EXCLUDED.city,address=EXCLUDED.address,opening_date=EXCLUDED.opening_date,status=EXCLUDED.status,monthly_revenue_target=EXCLUDED.monthly_revenue_target,monthly_profit_target=EXCLUDED.monthly_profit_target,food_cost_target_pct=EXCLUDED.food_cost_target_pct,labour_cost_target_pct=EXCLUDED.labour_cost_target_pct,updated_at=NOW() RETURNING id`;}
 if(parsed.data.type==="daily_sales"){await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(outlet_code text,business_date date,gross_sales numeric,net_sales numeric,orders int,discounts numeric,refunds numeric,tax numeric)) INSERT INTO daily_sales(outlet_id,business_date,gross_sales,net_sales,orders,discounts,refunds,tax,source) SELECT o.id,x.business_date,x.gross_sales,x.net_sales,x.orders,x.discounts,x.refunds,x.tax,'csv' FROM input x JOIN outlets o ON o.code=x.outlet_code ON CONFLICT(outlet_id,business_date) DO UPDATE SET gross_sales=EXCLUDED.gross_sales,net_sales=EXCLUDED.net_sales,orders=EXCLUDED.orders,discounts=EXCLUDED.discounts,refunds=EXCLUDED.refunds,tax=EXCLUDED.tax,source='csv',updated_at=NOW() RETURNING id`;}
 if(parsed.data.type==="channel_sales"){await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(outlet_code text,business_date date,channel text,gross_sales numeric,net_sales numeric,orders int,commission numeric,discounts numeric)) INSERT INTO channel_sales(outlet_id,business_date,channel_id,gross_sales,net_sales,orders,commission,discounts) SELECT o.id,x.business_date,c.id,x.gross_sales,x.net_sales,x.orders,x.commission,x.discounts FROM input x JOIN outlets o ON o.code=x.outlet_code JOIN sales_channels c ON c.code=x.channel ON CONFLICT(outlet_id,business_date,channel_id) DO UPDATE SET gross_sales=EXCLUDED.gross_sales,net_sales=EXCLUDED.net_sales,orders=EXCLUDED.orders,commission=EXCLUDED.commission,discounts=EXCLUDED.discounts,updated_at=NOW() RETURNING id`;}
 if(parsed.data.type==="expenses"){await tx`WITH input AS (SELECT DISTINCT period FROM jsonb_to_recordset(${payload}::jsonb) AS x(period text)) INSERT INTO reporting_periods(year,month,status) SELECT split_part(period,'-',1)::int,split_part(period,'-',2)::int,'open' FROM input ON CONFLICT(year,month) DO NOTHING`;
 await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(outlet_code text,period text,expense_date date,category text,vendor_name text,reference_no text,amount numeric,description text)) INSERT INTO expenses(outlet_id,period_id,expense_date,category_id,vendor_name,reference_no,amount,description,created_by) SELECT o.id,p.id,x.expense_date,c.id,NULLIF(x.vendor_name,''),NULLIF(x.reference_no,''),x.amount,NULLIF(x.description,''),${profile.id} FROM input x JOIN outlets o ON o.code=x.outlet_code JOIN expense_categories c ON c.code=x.category JOIN reporting_periods p ON p.year=split_part(x.period,'-',1)::int AND p.month=split_part(x.period,'-',2)::int RETURNING id`;}
 if(parsed.data.type==="staff"){await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(employee_code text,full_name text,role_title text,outlet_code text,joining_date text,status text,monthly_salary text,monthly_cost text)) INSERT INTO staff_members(employee_code,full_name,role_title,home_outlet_id,joining_date,status,current_monthly_salary,salary_effective_from,monthly_cost) SELECT x.employee_code,x.full_name,x.role_title,o.id,NULLIF(x.joining_date,'')::date,x.status,NULLIF(x.monthly_salary,'')::numeric,CASE WHEN NULLIF(x.monthly_salary,'') IS NOT NULL THEN NULLIF(x.joining_date,'')::date END,NULLIF(x.monthly_cost,'')::numeric FROM input x JOIN outlets o ON o.code=x.outlet_code ON CONFLICT(employee_code) DO UPDATE SET full_name=EXCLUDED.full_name,role_title=EXCLUDED.role_title,home_outlet_id=EXCLUDED.home_outlet_id,joining_date=EXCLUDED.joining_date,status=EXCLUDED.status,current_monthly_salary=EXCLUDED.current_monthly_salary,salary_effective_from=COALESCE(staff_members.salary_effective_from,EXCLUDED.salary_effective_from),monthly_cost=EXCLUDED.monthly_cost,updated_at=NOW() RETURNING id`;}

 if(parsed.data.type==="staff"){await tx`WITH input AS (SELECT DISTINCT employee_code FROM jsonb_to_recordset(${payload}::jsonb) AS x(employee_code text)) INSERT INTO staff_salary_history(staff_id,effective_from,monthly_salary,previous_monthly_salary,change_type,notes,changed_by) SELECT s.id,COALESCE(s.salary_effective_from,s.joining_date,CURRENT_DATE),s.current_monthly_salary,NULL,'joining','Imported staff salary',${profile.id} FROM staff_members s JOIN input i ON i.employee_code=s.employee_code WHERE s.current_monthly_salary IS NOT NULL AND NOT EXISTS(SELECT 1 FROM staff_salary_history h WHERE h.staff_id=s.id)`;}
 if(parsed.data.type==="monthly_financials"){await tx`WITH input AS (SELECT DISTINCT period FROM jsonb_to_recordset(${payload}::jsonb) AS x(period text)) INSERT INTO reporting_periods(year,month,status) SELECT split_part(period,'-',1)::int,split_part(period,'-',2)::int,'open' FROM input ON CONFLICT(year,month) DO NOTHING`;
 await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(outlet_code text,period text,gross_revenue numeric,net_revenue numeric,total_orders int,discounts numeric,refunds numeric,food_cost numeric,packaging_cost numeric,payroll_cost numeric,rent_cost numeric,utilities_cost numeric,aggregator_commission numeric,marketing_cost numeric,maintenance_cost numeric,other_operating_cost numeric,gross_profit numeric,operating_profit numeric,net_profit numeric,notes text)) INSERT INTO outlet_monthly_financials(outlet_id,period_id,gross_revenue,net_revenue,total_orders,discounts,refunds,food_cost,packaging_cost,payroll_cost,rent_cost,utilities_cost,aggregator_commission,marketing_cost,maintenance_cost,other_operating_cost,gross_profit,operating_profit,net_profit,notes,source) SELECT o.id,p.id,x.gross_revenue,x.net_revenue,x.total_orders,x.discounts,x.refunds,x.food_cost,x.packaging_cost,x.payroll_cost,x.rent_cost,x.utilities_cost,x.aggregator_commission,x.marketing_cost,x.maintenance_cost,x.other_operating_cost,x.gross_profit,x.operating_profit,x.net_profit,NULLIF(x.notes,''),'csv' FROM input x JOIN outlets o ON o.code=x.outlet_code JOIN reporting_periods p ON p.year=split_part(x.period,'-',1)::int AND p.month=split_part(x.period,'-',2)::int ON CONFLICT(outlet_id,period_id) DO UPDATE SET gross_revenue=EXCLUDED.gross_revenue,net_revenue=EXCLUDED.net_revenue,total_orders=EXCLUDED.total_orders,discounts=EXCLUDED.discounts,refunds=EXCLUDED.refunds,food_cost=EXCLUDED.food_cost,packaging_cost=EXCLUDED.packaging_cost,payroll_cost=EXCLUDED.payroll_cost,rent_cost=EXCLUDED.rent_cost,utilities_cost=EXCLUDED.utilities_cost,aggregator_commission=EXCLUDED.aggregator_commission,marketing_cost=EXCLUDED.marketing_cost,maintenance_cost=EXCLUDED.maintenance_cost,other_operating_cost=EXCLUDED.other_operating_cost,gross_profit=EXCLUDED.gross_profit,operating_profit=EXCLUDED.operating_profit,net_profit=EXCLUDED.net_profit,notes=EXCLUDED.notes,source='csv',updated_at=NOW() RETURNING id`;}
 if(parsed.data.type==="inventory"){await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(item_sku text,item_name text,unit text,category text)) INSERT INTO inventory_items(sku,name,unit,category) SELECT DISTINCT x.item_sku,x.item_name,x.unit,NULLIF(x.category,'') FROM input x ON CONFLICT(sku) DO UPDATE SET name=EXCLUDED.name,unit=EXCLUDED.unit,category=EXCLUDED.category,active=TRUE,updated_at=NOW()`;await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(outlet_code text,snapshot_date date,item_sku text,on_hand_qty numeric,unit_cost numeric,reorder_point text,wastage_qty numeric)) INSERT INTO inventory_snapshots(outlet_id,item_id,snapshot_date,on_hand_qty,unit_cost,reorder_point,wastage_qty) SELECT o.id,i.id,x.snapshot_date,x.on_hand_qty,x.unit_cost,NULLIF(x.reorder_point,'')::numeric,x.wastage_qty FROM input x JOIN outlets o ON o.code=x.outlet_code JOIN inventory_items i ON i.sku=x.item_sku ON CONFLICT(outlet_id,item_id,snapshot_date) DO UPDATE SET on_hand_qty=EXCLUDED.on_hand_qty,unit_cost=EXCLUDED.unit_cost,reorder_point=EXCLUDED.reorder_point,wastage_qty=EXCLUDED.wastage_qty RETURNING id`;}
 if(parsed.data.type==="vendors"){await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(vendor_code text,name text,category text,contact_name text,phone text,email text,payment_terms text,reliability_pct text,fill_rate_pct text,active text)) INSERT INTO vendors(code,name,category,contact_name,phone,email,payment_terms,reliability_pct,fill_rate_pct,active) SELECT x.vendor_code,x.name,NULLIF(x.category,''),NULLIF(x.contact_name,''),NULLIF(x.phone,''),NULLIF(x.email,''),NULLIF(x.payment_terms,''),NULLIF(x.reliability_pct,'')::numeric,NULLIF(x.fill_rate_pct,'')::numeric,x.active IN ('true','1') FROM input x ON CONFLICT(code) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,contact_name=EXCLUDED.contact_name,phone=EXCLUDED.phone,email=EXCLUDED.email,payment_terms=EXCLUDED.payment_terms,reliability_pct=EXCLUDED.reliability_pct,fill_rate_pct=EXCLUDED.fill_rate_pct,active=EXCLUDED.active,updated_at=NOW() RETURNING id`;}
 if(parsed.data.type==="purchases"){await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(outlet_code text,purchase_date date,vendor_code text,invoice_no text,subtotal numeric,tax numeric,total numeric,payment_status text)) INSERT INTO purchases(outlet_id,vendor_id,purchase_date,invoice_no,subtotal,tax,total,payment_status,created_by) SELECT o.id,v.id,x.purchase_date,NULLIF(x.invoice_no,''),x.subtotal,x.tax,x.total,x.payment_status,${profile.id} FROM input x JOIN outlets o ON o.code=x.outlet_code JOIN vendors v ON v.code=x.vendor_code ON CONFLICT(outlet_id,vendor_id,purchase_date,invoice_no) WHERE invoice_no IS NOT NULL DO UPDATE SET subtotal=EXCLUDED.subtotal,tax=EXCLUDED.tax,total=EXCLUDED.total,payment_status=EXCLUDED.payment_status,updated_at=NOW() RETURNING id`;}
 if(parsed.data.type==="menu_performance"){await tx`WITH input AS (SELECT DISTINCT period FROM jsonb_to_recordset(${payload}::jsonb) AS x(period text)) INSERT INTO reporting_periods(year,month,status) SELECT split_part(period,'-',1)::int,split_part(period,'-',2)::int,'open' FROM input ON CONFLICT(year,month) DO NOTHING`;await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(item_sku text,item_name text,category text)) INSERT INTO menu_items(sku,name,category) SELECT DISTINCT x.item_sku,x.item_name,NULLIF(x.category,'') FROM input x ON CONFLICT(sku) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,active=TRUE,updated_at=NOW()`;await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(outlet_code text,period text,item_sku text,quantity_sold int,net_sales numeric,estimated_food_cost text,contribution_margin text,refunds int)) INSERT INTO menu_performance_monthly(outlet_id,period_id,menu_item_id,quantity_sold,net_sales,estimated_food_cost,contribution_margin,refunds) SELECT o.id,p.id,m.id,x.quantity_sold,x.net_sales,NULLIF(x.estimated_food_cost,'')::numeric,NULLIF(x.contribution_margin,'')::numeric,x.refunds FROM input x JOIN outlets o ON o.code=x.outlet_code JOIN reporting_periods p ON p.year=split_part(x.period,'-',1)::int AND p.month=split_part(x.period,'-',2)::int JOIN menu_items m ON m.sku=x.item_sku ON CONFLICT(outlet_id,period_id,menu_item_id) DO UPDATE SET quantity_sold=EXCLUDED.quantity_sold,net_sales=EXCLUDED.net_sales,estimated_food_cost=EXCLUDED.estimated_food_cost,contribution_margin=EXCLUDED.contribution_margin,refunds=EXCLUDED.refunds,updated_at=NOW() RETURNING id`;}
 if(parsed.data.type==="cash_reconciliation"){await tx`WITH input AS (SELECT * FROM jsonb_to_recordset(${payload}::jsonb) AS x(outlet_code text,business_date date,expected_cash numeric,counted_cash numeric,banked_cash numeric,variance numeric,notes text)) INSERT INTO cash_reconciliations(outlet_id,business_date,expected_cash,counted_cash,banked_cash,variance,notes,reconciled_by,reconciled_at) SELECT o.id,x.business_date,x.expected_cash,x.counted_cash,x.banked_cash,x.variance,NULLIF(x.notes,''),${profile.id},NOW() FROM input x JOIN outlets o ON o.code=x.outlet_code ON CONFLICT(outlet_id,business_date) DO UPDATE SET expected_cash=EXCLUDED.expected_cash,counted_cash=EXCLUDED.counted_cash,banked_cash=EXCLUDED.banked_cash,variance=EXCLUDED.variance,notes=EXCLUDED.notes,reconciled_by=${profile.id},reconciled_at=NOW() RETURNING id`;}
 await tx`INSERT INTO data_import_jobs(id,import_type,original_filename,status,row_count,accepted_count,rejected_count,created_by,created_at,completed_at) VALUES(${jobId},${parsed.data.type},${parsed.data.filename},'imported',${validated.totalRows},${count},0,${profile.id},NOW(),NOW())`;
 await tx`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES(${profile.id},'import','data_import_job',${jobId},${JSON.stringify({type:parsed.data.type,filename:parsed.data.filename,rowCount:count})}::jsonb)`;
 });
 const postCommit=await Promise.allSettled([
  recordSecurityEvent("business_data_imported",{metadata:{type:parsed.data.type,rowCount:count,jobId}}),
  ...(parsed.data.type!=="outlets"&&parsed.data.type!=="vendors"?[refreshControlAlerts()]:[])
 ]);
 const warnings=postCommit.filter(result=>result.status==="rejected").length;
 if(warnings)console.error(`Import ${jobId} committed with ${warnings} post-commit warning(s)`);
 return Response.json({ok:true,imported:count,jobId,warnings},{headers:{"Cache-Control":"no-store"}});
 }catch(error){const response=requestParseError(error);if(response)return response;return internalApiError(error,"Import failed and was rolled back","IMPORT_COMMIT_FAILED");}}
