import { z } from "zod";
import { requireApiProfile } from "@/lib/access-control";
import { recordBusinessAudit,recordSecurityEvent } from "@/lib/audit";
import { db } from "@/lib/db";
import { consumeRateLimit,enforceSameOrigin,rateLimitResponse,readJsonWithLimit,requestParseError } from "@/lib/http-security";
import { hasFreshFinancialMfa } from "@/lib/mfa";
const dateOrNull=z.union([z.string().regex(/^\d{4}-\d{2}-\d{2}$/),z.null()]);const base=z.object({id:z.string().uuid().optional(),code:z.string().trim().min(2).max(20).regex(/^[A-Za-z0-9_-]+$/),name:z.string().trim().min(2).max(120),legalName:z.string().trim().max(180).optional(),city:z.string().trim().min(2).max(100).default("Bengaluru"),address:z.string().trim().max(500).optional(),openingDate:dateOrNull.default(null),status:z.enum(["planned","active","temporarily_closed","closed"]).default("active"),monthlyRevenueTarget:z.number().min(0).max(1_000_000_000).nullable().optional(),monthlyProfitTarget:z.number().min(-1_000_000_000).max(1_000_000_000).nullable().optional(),foodCostTargetPct:z.number().min(0).max(100).nullable().optional(),labourCostTargetPct:z.number().min(0).max(100).nullable().optional()});
export async function GET(){const a=await requireApiProfile("/api/outlets");if("response" in a)return a.response;const rows=await db()`SELECT id,code,name,legal_name,city,address,opening_date,status,monthly_revenue_target,monthly_profit_target,food_cost_target_pct,labour_cost_target_pct FROM outlets ORDER BY name`;return Response.json({rows},{headers:{"Cache-Control":"private, no-store"}})}
async function write(req:Request,method:"create"|"update"){const same=enforceSameOrigin(req);if(same)return same;const a=await requireApiProfile("/api/outlets");if("response" in a)return a.response;if(!(await hasFreshFinancialMfa()))return Response.json({error:"Fresh MFA required",code:"MFA_FRESH_REQUIRED"},{status:428});const lim=await consumeRateLimit("outlet-write",20,60,"user");if(!lim.allowed)return rateLimitResponse(lim.retryAfter);try{const p=base.safeParse(await readJsonWithLimit(req,16000));if(!p.success)return Response.json({error:"Invalid outlet record",issues:p.error.flatten()},{status:400});const v=p.data;if(method==="create"){const rows=await db()`INSERT INTO outlets(code,name,legal_name,city,address,opening_date,status,monthly_revenue_target,monthly_profit_target,food_cost_target_pct,labour_cost_target_pct) VALUES(${v.code.toUpperCase()},${v.name},${v.legalName||null},${v.city},${v.address||null},${v.openingDate},${v.status},${v.monthlyRevenueTarget??null},${v.monthlyProfitTarget??null},${v.foodCostTargetPct??null},${v.labourCostTargetPct??null}) RETURNING *`;const r=rows[0] as any;await recordBusinessAudit({actorUserId:a.profile.id,action:"create",entityType:"outlet",entityId:String(r.id),outletId:String(r.id),newValues:r});await recordSecurityEvent("outlet_created",{metadata:{outletId:String(r.id),code:r.code}});return Response.json({ok:true,row:r});}if(!v.id)return Response.json({error:"Outlet id required"},{status:400});const old=(await db()`SELECT * FROM outlets WHERE id=${v.id}`)[0] as any;if(!old)return Response.json({error:"Outlet not found"},{status:404});const rows=await db()`UPDATE outlets SET code=${v.code.toUpperCase()},name=${v.name},legal_name=${v.legalName||null},city=${v.city},address=${v.address||null},opening_date=${v.openingDate},status=${v.status},monthly_revenue_target=${v.monthlyRevenueTarget??null},monthly_profit_target=${v.monthlyProfitTarget??null},food_cost_target_pct=${v.foodCostTargetPct??null},labour_cost_target_pct=${v.labourCostTargetPct??null},updated_at=NOW() WHERE id=${v.id} RETURNING *`;const r=rows[0] as any;await recordBusinessAudit({actorUserId:a.profile.id,action:"update",entityType:"outlet",entityId:v.id,outletId:v.id,oldValues:old,newValues:r});return Response.json({ok:true,row:r});}catch(e){const r=requestParseError(e);if(r)return r;return Response.json({error:e instanceof Error?e.message:"Outlet write failed"},{status:400});}}
export async function POST(req:Request){return write(req,"create")}export async function PATCH(req:Request){return write(req,"update")}
